### ISSUE TITLE
Document vscode-ruby

### ISSUE THREAD

**Issue by searls** [testdouble/standard#100]
We should document setup instructions for standard under the editor section of the README (see: https://github.com/rubyide/vscode-ruby )

**Comment by stevenharman** [comment]
Does this supersede #44?

**Comment by ribordy** [comment]
I think this might be done as of the newest version of `vscode-ruby`, see here: https://github.com/rubyide/vscode-ruby/blob/master/docs/linting.md#standard

**Comment by searls** [comment]
Hey @jasonkarns, as keeper of the standard wiki would you like to take a couple screenshots of setting this up for us? 😊

**Comment by jasonkarns** [comment]
I'm going to punt this over to someone who has or uses vscode.

**Comment by ribordy** [comment]
I'm willing to take a stab at it over the weekend!

**Comment by ribordy** [comment]
I'm not sure what the right way to contribute a change to the wiki, but here's a simple set of instructions to getting linting enabled in vscode:

1. Install the [Ruby extension](https://github.com/rubyide/vscode-ruby)
2. Enable the Ruby language server in your settings:
![ruby language server](https://user-images.githubusercontent.com/2159914/64479824-61925380-d171-11e9-80b5-94e1f35392ab.PNG)
3. The Ruby:Lint option will direct you to the `settings.json` file:
    ![ruby linting](https://user-images.githubusercontent.com/2159914/64479827-67883480-d171-11e9-80c6-1c876bef469f.png)
Enable standard linting by adding the following: 
    ```json
    "ruby.lint": {
      "standard": true
    }
    ```
4. Reload your window to enable the language server and linting. You can confirm that linting is happening by selecting the "Ruby Language Server" in the Output tab.

You can view the [ruby extension docs](https://github.com/rubyide/vscode-ruby/blob/master/docs/linting.md#standard) for more configuration options, like defaulting to the bundler-installed version of standard:
```json
"ruby.lint": {
  "standard": {
    "useBundler": true,
  }
}
```

**Comment by jasonkarns** [comment]
Thanks @ribordy! copied almost verbatim: https://github.com/testdouble/standard/wiki/IDE:-vscode

**Comment by searls** [comment]
Thanks a bunch for this!
