### ISSUE TITLE
Incompatibility with rubocop version 0.67

### ISSUE THREAD

**Issue by ianagne** [testdouble/standard#104]
Hi ya'll,

I'm loving standard ❤️ 

I noticed today that rubocop moved some of its performance cops to the style section in version 0.67,.  This causes the standardrb executable to fail with the following errors:

```
Performance/RedundantSortBy has the wrong namespace - should be Style
Performance/Sample has the wrong namespace - should be Style
Performance/UnneededSort has the wrong namespace - should be Style
```

Rubocop version 0.66 works well. I opened #103 to restrict the version to <= 0.66 as a potential solution.

**Comment by searls** [comment]
Thanks for reporting, fixing with: bce3a18013a227319ccc6a797d3e4a076dc4ef73

**Comment by searls** [comment]
This does raise an interesting problem in #105, though. Opinions welcome!
