### ISSUE TITLE
Proposal: Enforce Layout/SpaceInsideBlockBraces

### ISSUE THREAD

**Issue by pmk1c** [testdouble/standard#106]
Regarding the rule `Layout/SpaceInsideBlockBraces` Standard wants to enforce a "consistent" Style (*either* spaces at the beginning *and* the end of block braces, *or* none at all). This setting is currently not available in Rubocop, so the cop is disabled completely.

Why don't we enforce one style instead of allowing both? I'd love this linting standard to be strict in these cases. Although I'm not strongly biased, I'd probably prefer enforcing spaces in this case. This makes it easier to distinguish between hashes and blocks with braces.

**Comment by schneems** [comment]
How did you enable that setting? I just want my style to be consistent.

Rails codebase uses spaces `{ |like| this + like }`

**Comment by searls** [comment]
Sorry that I didn't follow up on this. It was because I literally thought we were already doing this and forgot that we weren't. See https://github.com/testdouble/standard/commit/a0d13110f2c54345eb3b0c4aaa31fe7169b6027c

**Comment by samphippen** [comment]
💯

**Comment by searls** [comment]
LOL, and to add to the confusion I literally wrote the wrong headline in the commit. I meant enforce spaces inside blocks.

Ok, I'm going to go weekend now thanks bye
