### ISSUE TITLE
Warning when required

### ISSUE THREAD

**Issue by mperham** [testdouble/standard#107]
Sidekiq is using Standard, thanks for this project Justin and team!

Since I run with warnings enabled, I see this when my test suite runs.

```
/Users/mikeperham/.gem/ruby/2.6.1/gems/parser-2.6.2.1/lib/parser/lexer.rb:10862: warning: assigned but unused variable - testEof
/Users/mikeperham/.gem/ruby/2.6.1/gems/standard-0.0.37/lib/standard/rubocop/ext.rb:3: warning: method redefined; discarding old message
/Users/mikeperham/.gem/ruby/2.6.1/gems/rubocop-0.67.2/lib/rubocop/cop/lint/assignment_in_condition.rb:51: warning: previous definition of message was here
```

Mayhaps one or more can be fixed easily?

**Comment by searls** [comment]
Hey Mike, thanks for reporting this! Unfortunately I personally won't have time to look at this right away, but would absolutely love if you could spend a few minutes poking at it.

Enough people care about exiting cleanly without warnings that I think our CI build should probably fail when they're emitted to catch these in the future as best we can
