### ISSUE TITLE
Performance/TimesMap: Use `Array.new(3)` with a block instead of `.times.map`.

### ISSUE THREAD

**Issue by JoshTGreenwood** [testdouble/standard#11]
In my experience, when I use `[N].times.map`, it is nearly always when N is a small number less than 5. In all the cases I found in the codebase I'm currently working in, I found readability was hurt by this rule far more than performance would have been saved.

What do you think about shutting this rule off?

**Comment by searls** [comment]
coincidentally fixed by 149e604bbfb71c09b59efbabdd60502140516d3c

**Comment by searls** [comment]
Landed in v0.0.8
