### ISSUE TITLE
spaces inside hashes

### ISSUE THREAD

**Issue by localhostdotdev** [testdouble/standard#116]
```diff
-    { message: response.body }
+    {message: response.body}
```

tried it on my small codebase and I have zero issue with it (e.g. it matches my coding style pretty closely) except for those spaces inside hashes.

maybe the reasoning is to differentiate from blocks.

to be honest I don't have a strong reasoning for this except that I think the "no-space" style is too compact and the "spaces" is more "readable" to me.

**Comment by searls** [comment]
This is intentional. And yes, the reasoning is to differentiate from blocks.

**Comment by searls** [comment]
More discussion here. https://github.com/testdouble/standard/issues/26

**Comment by localhostdotdev** [comment]
another argument would be that this is different from what most codebases do and what other formatters do, then it's imposing a change on most people's habits.

anyway, will add my config line :D
