### ISSUE TITLE
Compatibility with ruby 2.7

### ISSUE THREAD

**Issue by hurricup** [testdouble/standard#119]
Attempt to run standardrb on ruby-27 fails, probably because of rubocop's version. Would be nice to address this.

**Comment by searls** [comment]
I think this will involve implementing #105 by upgrading rubocop, pulling in rubocop-performance, and making sure everything passes

**Comment by searls** [comment]
Thanks @koic!

**Comment by JamesChevalier** [comment]
I think this was resolved by https://github.com/testdouble/standard/pull/126

**Comment by searls** [comment]
Yup!
