### ISSUE TITLE
Assignations rule

### ISSUE THREAD

**Issue by pablocrivella** [testdouble/standard#127]
I'm not sure if rubocop recommends or enforces any type of rule for assignations.
I have seen that some people like to align assignations on the equals operator like:

```ruby
foo       = 1
bar       = 2
foobar    = 3
foobarbas = 4
``` 

IMHO, I think standardrb should just default to not aligning on the equals (like the golang formatter does)
```ruby
foo = 1
bar = 2
fopbaar = 3
foobarbas = 4
```

I don't have strong arguments against the 1st option other than sometimes looks really ugly (subjective), it's width inefficient and you have to remember to update the other assignations (this could be solved by the formatter).

**Comment by searls** [comment]
I expected standardrb to already do this, and was surprised when it didn't.

```ruby
foo       = 1
bar       = 2
foobar    = 3
foobarbas = 4

puts "#{foo} #{bar} #{foobar} #{foobarbas}"
```

Should `standardrb --fix` to:

```
foo = 1
bar = 2
foobar = 3
foobarbas = 4

puts "#{foo} #{bar} #{foobar} #{foobarbas}"
```

**Comment by pablocrivella** [comment]
🤔 It didn't work in this scenario for example:

```ruby
Gem::Specification.new do |spec|
  spec.name     = "bar"
  spec.email    = ["foo@gmail.com"]
  spec.license  = "MIT"
  spec.version  = Bar::VERSION
  spec.authors  = ["Foo bar"]
  spec.homepage = "https://github.com/foo/bar"
  spec.summary  = "Foo bar."
  spec.metadata = {
    "bug_tracker_uri" => "https://github.com/foo/bar/issues",
    "changelog_uri" => "https://github.com/foo/bar/blob/master/CHANGELOG.md",
    "source_code_uri" => "https://github.com/foo/bar",
  }
  # ...
end
```

**Comment by searls** [comment]
No, it doesn't currently do this, but it should.

**Comment by pablocrivella** [comment]
Oh I missunderstod 😅

**Comment by pablocrivella** [comment]
I couldn't find an option on rubocop to force this... not sure if it ever worked tbh...

**Comment by pablocrivella** [comment]
@searls Do you know if there's an issue for this on the rubocop gem? So far I couldn't find anything

**Comment by searls** [comment]
Sorry, I'm unsure if this is possible in Rubocop and haven't had time to look at standard for a couple weeks—maybe open an issue to ask the rubocop folks?

**Comment by pablocrivella** [comment]
Thanks for replying :) Let's see if we get any answer on this issue I created on the rubocop repo: https://github.com/rubocop-hq/rubocop/issues/7269

**Comment by pablocrivella** [comment]
@searls adding this setting fixes the issue:

```yml
Layout/ExtraSpacing:
  AllowForAlignment: false
```

Do you want me to make a PR to add it to `config/base.yml`?
