### ISSUE TITLE
Lint/AmbiguousBlockAssociation for classic expect/change RSpec idiom

### ISSUE THREAD

**Issue by elia** [testdouble/standard#129]
```rb
it "does something" do
  expect { subject }.not_to change { something_else }
end
```

This kind of lines are generating a bunch of `Lint/AmbiguousBlockAssociation`, but putting parens around the argument as in `expect(…).not_to (change {…})` defeats the whole RSpec syntax-sugar thing… 

It's also not less ambiguous, mainly because to any RSpec user (and I dare say to any Ruby programmer) the line is quite clear.

**Comment by searls** [comment]
Agree. Released in 0.1.1
