### ISSUE TITLE
Create GitHub action for Standard

### ISSUE THREAD

**Issue by pcriv** [testdouble/standard#131]
Could be approached on a similar way to: https://github.com/marketplace/actions/rubocop-checks

**Comment by cored** [comment]
@pablocrivella Started working on this today: https://github.com/cored/standard-action planning on releasing a stable version next week :wave:

**Comment by pablocrivella** [comment]
Looks good @amoeba  I'll try to integrate it with a repo of mine soon

**Comment by pablocrivella** [comment]
@cored Did you manage to get your fork working? Also, does it make sense to have 2 of the same thing?

**Comment by amoeba** [comment]
Hey @pablocrivella did you get a chance to try it out?

**Comment by camilopayan** [comment]
Would love to get your feedback on this action! Going to close this, so issues can go on the action if you have anything there.

https://github.com/testdouble/standardrb-action

**Comment by krystof-k** [comment]
This issue should be reopened as there is not a single working GitHub Action (except [this one](https://github.com/marketplace/actions/run-standard-with-reviewdog) using [reviewdog](https://github.com/reviewdog/reviewdog))…
