### ISSUE TITLE
Trailing comma rule results in `},])` contortion

### ISSUE THREAD

**Issue by searls** [testdouble/standard#133]
Standard keeps slamming the final `,` into this and I hate it:

```ruby
    Item.find_by_sql([sql, {
      user_id: user.id,
      answer: answer,
    },]).uniq
```

There's no way anyone thinks `},])` is preferable in this case, right?

**Comment by pablocrivella** [comment]
Yup, I don't like it either 😬 
Would the solution be only adding the comma to the last element of a hash?

**Comment by searls** [comment]
Yes, one would think

**Comment by GeoffAbtion** [comment]
`},]) ` is undesirable but I think it is a symptom of another problem, you're trying to wrap a hash in a strange way. Of course that is going to look wrong.

These all look reasonable:

1)
```ruby
Item.find_by_sql(
  [
    sql,
    {
      user_id: user.id,
      answer: answer,
    },
  ]
).uniq
```
2)
```ruby
Item.find_by_sql([
  sql,
  {
    user_id: user.id,
    answer: answer,
  },
]).uniq
```
3)
```ruby
Item.find_by_sql([
  sql,
  {user_id: user.id, answer: answer},
]).uniq
```
4)
```ruby
Item.find_by_sql([sql, {user_id: user.id, answer: answer}]).uniq
```

2) is probably what I'd want to see.

**Comment by jmkoni** [comment]
Pretty sure we fixed this in https://github.com/testdouble/standard/commit/a7156b14528f4b171567c528f6a2434a43b6e54a
