### ISSUE TITLE
Disable Bundler/DuplicatedGem

### ISSUE THREAD

**Issue by searls** [testdouble/standard#134]
`Bundler/DuplicatedGem` will flag this:

```
if ENV["RAILS_NEXT"]
  gem "rails", "~> 5.1.0"
else
  gem "rails", "~> 5.0.0"
end
```

Which is in fact a very valid thing to do if you're [upgrading rails](http://blog.testdouble.com/posts/2019-09-03-3-keys-to-upgrading-rails) by using [bootboot](http://blog.testdouble.com/posts/2019-09-03-3-keys-to-upgrading-rails). I think we should disable this one

**Comment by etagwerker** [comment]
I see that the false positive has been fixed in rubocop: https://github.com/rubocop/rubocop/pull/8666 -- so this is probably a wrong version issue on my side...
