### ISSUE TITLE
Layout/AlignArguments cop should be enabled, but not sure with which setting is best

### ISSUE THREAD

**Issue by joeyschoblaska** [testdouble/standard#136]
I feel like this cop should be enabled to enforce consistent alignment of arguments, but I'm not sure which setting fits better with the current rules.

### Input
```ruby
method(:one,
   :two,
     three: four)

method(:one,
    three: four)

method(one: two,
   three: four)

method(
  :one,
          :two
)

foo :bar,
      :baz

def foo(bar,
        baz)
  123
end
```

### Current behavior
```ruby
method(:one,
   :two,
     three: four)

method(:one,
    three: four)

method(one: two,
       three: four)

method(
  :one,
          :two
)

foo :bar,
      :baz

def foo(bar,
  baz)
  123
end
```

### Layout/AlignArguments enabled, with_fixed_indentation
Using `with_fixed_indentation` is nice because it matches Layout/AlignParameters

```ruby
method(:one,
  :two,
  three: four)

method(:one,
  three: four)

method(one: two,
       three: four) # formatted by Layout/AlignHash

method(
  :one,
  :two
)

foo :bar,
  :baz

def foo(bar,
  baz) # formatted by Layout/AlignParameters
  123
end
```

### Layout/AlignArguments enabled, with_first_argument
Using `with_first_argument` is nice because it matches how Layout/AlignHash formats multi-line arguments that are all key / value pairs.

```ruby
method(:one,
       :two,
       three: four)

method(:one,
       three: four)

method(one: two,
       three: four) # formatted by Layout/AlignHash

method(
  :one,
  :two
)

foo :bar,
    :baz

def foo(bar,
  baz) # formatted by Layout/AlignParameters
  123
end
```

**Comment by searls** [comment]
Thanks a lot for this summary. I think that `with_fixed_indentation` best matches the spirit of standard's other alignment rules, which are basically "always indent relative to the indentation of the parent expression", as opposed to some arbitrary level of indentation to match up with an arg or key position
