### ISSUE TITLE
Example/Test code for SemanticBlocks?

### ISSUE THREAD

**Issue by Insti** [testdouble/standard#143]
@searls do you remember which code you were using standard on when writing the [SemanticBlocks](https://github.com/testdouble/standard/blob/master/lib/standard/cop/semantic_blocks.rb) code?

I'm trying to fill out the test coverage for the file, and it might be easier to have some example code rather than needing to reverse-engineer test cases.

**Comment by searls** [comment]
I didn't write the implementation. This file was a fork of the impl in rubocop itself

**Comment by Insti** [comment]
Ok, thanks, I'll go digging around and see what I can find there.
