### ISSUE TITLE
Guard clause plus favouring unless is confusing

### ISSUE THREAD

**Issue by mvz** [testdouble/standard#146]
I always have to pause figuring out the logic of guard clauses with `unless`. For example: Should `config` be a document or not:

```ruby
def do_thing(config)
  return unless config.document?

  do_other_thing(config)
  do_more(config)
end
```

The double negation makes this harder to read than necessary: Don't do this unless this thing is true.

Slightly easier somehow:

```ruby
def do_thing(config)
  return if !config.document?

  do_other_thing(config)
  do_more(config)
end
```

Super-clear:

```ruby
def do_thing(config)
  if config.document?
    do_other_thing(config)
    do_more(config)
  end
end
```

I generally agree with the two rules that together lead to the first version, but in combination I don't like the result. How can we resolve this?

**Comment by mvz** [comment]
Here's another option (currently also not allowed, but `||` look weird here I think):

```ruby
def do_thing(config)
  config.document? or return

  do_other_thing(config)
  do_more(config)
end
```

**Comment by searls** [comment]
Thanks for sharing your thoughts! For what it's worth, I think `return unless X` guard clauses are straightforward and comprehensible, but I'm open to hearing more opinions from folks, of course!
