### ISSUE TITLE
Plans for a pronto runner?

### ISSUE THREAD

**Issue by julianrubisch** [testdouble/standard#147]
I use [pronto](https://github.com/prontolabs/pronto) extensively on a daily basis for code review. 

Are there any plans building a runner for pronto? Or can it somehow simply be forwarded to the rubocop runner? (asking ignorantly)

I haven't yet written any pronto runners myself, but it looks quite straightforward: https://kevinjalbert.com/create-your-own-pronto-runner/

Please ping me if that's an interesting option for you and I can be of help.

**Comment by searls** [comment]
Hi Julian, thanks for reaching out. I actually hadn't heard of Pronto before, so I hadn't heard of anyone else having plans to integrate with it. If it'd help you out to have one, go for it!

**Comment by julianrubisch** [comment]
Great! I’ll see what I can do and report back.

**Comment by julianrubisch** [comment]
Could you point me to an entry point from where to start a runner? probably just https://github.com/testdouble/standard/blob/master/lib/standard/cli.rb#L15 ?

**Comment by searls** [comment]
That's probably the best bet to see if you can get working. YMMV since reading that class it obviously wasn't intended as a non-CLI API

**Comment by julianrubisch** [comment]
I did it! Basically just a case of subclassing the rubocop runner 💯 :

https://github.com/julianrubisch/pronto-standardrb

**Comment by searls** [comment]
LOL, yes this appears to be the one-true-way of writing extension tooling for Standard

**Comment by searls** [comment]
Ok, added it to the README! 🚀
