### ISSUE TITLE
Strange indentation for method defined after line continuation

### ISSUE THREAD

**Issue by twe4ked** [testdouble/standard#163]
```ruby
# 1. Weird indentation that standard is happy with:
private \
  def foo
  123
end

# 2. Doesn't like this:
# Layout/FirstParameterIndentation: Indent the first parameter one step more than the start of the previous line.
private \
def bar
  123
end

# 3. Doesn't like this either:
# Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
# Layout/DefEndAlignment: `end` at 14, 2 is not aligned with `private \   def` at 11, 0.
private \
  def baz
    123
  end
```

I think examples 2 or 3 are nicer than 1. If there is some consensus I can have a look to see if there's a way get it to behave. Thoughts?

**Comment by searls** [comment]
I suppose 2 is right, but I suspect this will be difficult to implement using Rubocop's existing rules. 

FWIW, I wouldn't budget too much time into this… in 15 years I think I've seen `\` used only three or four times to continue a line, and each time it was to concatenate strings in ways I would have preferred to use a heredoc for

**Comment by twe4ked** [comment]
You're right. It doesn't seem to be something that can be allowed with the currently available cops AFAICT. Closing for now.
