### ISSUE TITLE
A case for `Style/AccessModifierDeclarations` set to `inline`

### ISSUE THREAD

**Issue by bjeanes** [testdouble/standard#17]
Hey @searls, hope you're well!

I love the idea of this and am generally supportive. I thought I'd start comparing to my own set of rubocop styles and make a case for ones I have configured for reasons I believe to be tied to code quality/readability/etc vs just "because I like the way it looks"

First on my list, `Style/AccessModifierDeclarations`.

I believe a mis-feature in Ruby is that accessibility modifiers are stateful, in that once `private` is called, all methods defined later in the module/class have their accessibility modified. Various ways of identifying non-public methods have come and fallen out of vogue over the years, like the indent-an-extra-2-spaces pattern, but none of them really help you understand any given method in context, without scrolling up.

In my codebase(s), I have a strict rule of:

```yml
# In-lining access modifiers removes risk of accidentally changing access level
# when re-ordering methods and improves clarity about method access
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
```

This affects code like so:

```ruby
class BadStyle
  def public_1; end

  private

  def private_1; end
  def private_2; end

  protected

  def protected_1; end

  private

  def private_3; end # wat

  public

  def public_2; end # wat
end

class BetterStyle
  def public_1; end

  private def private_1; end
  private def private_2; end
  protected def protected_1; end
  private def private_3; end
  def public_2; end
end
```

I know this can be somewhat un-Rubyish and more like other languages, but I think it's clearly superior. It keeps accessibility scope tied directly to the method(s) it should effect and it limits their effect to only those methods; it is more immune to inadvertent changes in accessibility during refactoring; and it makes is always much clearer what accessibility the current, in-view method is at all times.

This doesn't work on older Rubies, though I don't recall which versions exactly. It works for every Ruby in which `def` returns the symbol name of the method just defined, so is equivalent to:

```ruby
def x
end
private :x
```

What do you think?

_N.B. I just got out of collar bone surgery a few hours ago so I might be a tad out of it. So, if any of this doesn't make sense or isn't persuasive, I'd be very happy to follow up with any questions, comments, or objections._

**Comment by searls** [comment]
First and foremost, I hope you recover quickly from your surgery!

My snap opinion was to think that this is too far from the norm to be readily accepted by folks. After thinking for a bit, here's why I think I'm :-1: on it:

I came to Ruby from Java in large part because Ruby's sharp edges conferred a certain _trust_ to the developer. Ruby doesn't require you to repeat yourself (as Java did) as if to convey a pessimistic outlook on programmers' attentiveness. Put differently, this feels like it would be penalizing everyone with added verbosity for the sake of preventing carelessness by a few.

**Comment by bjeanes** [comment]
Ack!
