### ISSUE TITLE
How can I format standardrb output exactly like rubocop?

### ISSUE THREAD

**Issue by alirezabashyri** [testdouble/standard#170]
```
app/models/order.rb:231:7: C: Layout/DotPosition: Place the . on the previous line, together with the method call receiver.
```

The above output is Rubocop format how can I achieve that with standardrb?

**Comment by searls** [comment]
Per the README, passing `--format` with any built-in Rubocop formatter should work: https://docs.rubocop.org/en/latest/formatters/
