### ISSUE TITLE
Add Ruby 2.4 bound on newer versions

### ISSUE THREAD

**Issue by Pr0p1k** [testdouble/standard#171]
Since standard 0.3.0 depends on RuboCop 0.82, it's required Ruby version >=0 is obsolete, because RuboCop 0.82 needs Ruby >=2.4.0.

**Comment by searls** [comment]
Thanks, but I don't believe it's necessary for Standard to declare its Ruby support, since RubyGems is smart enough to fail installation. Standard's own code doesn't do anything to preclude earlier versions of Ruby so I don't want to signal that it does by constraining the gemspec. Additionally, even though we're constrained by RuboCop's 2.4+ requirement at _runtime_, Standard still works fine for linting source listings as old as 1.8

In any case I just tested that for people running 2.3, installing standard will fail:

```
$ gem install standard
Fetching: jaro_winkler-1.5.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed jaro_winkler-1.5.4
Fetching: parallel-1.19.1.gem (100%)
Successfully installed parallel-1.19.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.7.1.2.gem (100%)
Successfully installed parser-2.7.1.2
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: rexml-3.2.4.gem (100%)
Successfully installed rexml-3.2.4
Fetching: ruby-progressbar-1.10.1.gem (100%)
Successfully installed ruby-progressbar-1.10.1
Fetching: unicode-display_width-1.7.0.gem (100%)
Successfully installed unicode-display_width-1.7.0
Fetching: rubocop-0.82.0.gem (100%)
ERROR:  Error installing standard:
	rubocop requires Ruby version >= 2.4.0.
```

Which is good enough for me.

**Comment by hurricup** [comment]
@searls the point is not only fail safity. 

E.g. when I'm installing `rubocop`, I'm getting informative message:
```
ERROR:  Error installing rubocop:
	The last version of rubocop (>= 0) to support your Ruby & RubyGems was 0.81.0. Try installing it with `gem install rubocop -v 0.81.0`
	rubocop requires Ruby version >= 2.4.0. The current ruby version is 2.3.0.
```
And it's obvious how should I adjust the command to get what I want. (ofc. I'd prefer `rubygems` to re-run proper command for me, but this is a different story).

In other hand, when I'm trying to install `standard`, i'm getting the same `rubocop` error message. And what should I do? Go to rubygems.org and manually browse standard versions and check dependencies? Not really friendly behavior, don't you think so?

**Comment by searls** [comment]
Okay, that's reasonable

**Comment by hurricup** [comment]
To achieve the goal I described this need to be backported to the last released version.  Because after releasing this change, rubygems will recommend ot use previous version for ruby < 2.4 and it will fail with rubocop error.
