### ISSUE TITLE
Misalignment with method definition + macro + ensure

### ISSUE THREAD

**Issue by sobrinho** [testdouble/standard#178]
Hey!

```ruby
my_macro def something
  blah
ensure
  other_blah
end
```

Running `standardrb --fix` it changes it to:

```ruby
my_macro def something
  blah
         ensure
           other_blah
end
```

I expected no changes to it.

**Comment by searls** [comment]
How does default Rubocop behave with this? If it's similarly mangled it might be more expedient to log this as a rubocop bug

**Comment by searls** [comment]
And if not, please take a look through the relevant cop configurations we have in `config/base.yml` and tinker with them to see if you can get it how you'd expect

**Comment by sobrinho** [comment]
Good question, let me check what happens with plain rubocop.

**Comment by sobrinho** [comment]
Same behavior with plain rubocop and no configuration, I will report against it, thanks!
