### ISSUE TITLE
Why standard does not require parentheses by default?

### ISSUE THREAD

**Issue by milushov** [testdouble/standard#180]
EnforcedStyle: require_parentheses (default)

```ruby
# bad
array.delete e

# good
array.delete(e)

# good
# Operators don't need parens
foo == bar

# good
# Setter methods don't need parens
foo.bar = baz

# okay with `puts` listed in `IgnoredMethods`
puts 'test'

# okay with `^assert` listed in `IgnoredPatterns`
assert_equal 'test', x
```

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MethodCallWithArgsParentheses

**Comment by searls** [comment]
Because I want Standard to be used by Rubyists everywhere, even if they happen to reside in [Seattle](https://whydavewhy.com/2013/09/05/parentheses-in-ruby/comment-page-1/)
