### ISSUE TITLE
Support standardrb:disable comment directives

### ISSUE THREAD

**Issue by twe4ked** [testdouble/standard#184]
Would you be open to supporting `standardrb:disable` comments? Looks like we could maybe monkey patch [`RuboCop::CommentConfig`](https://github.com/rubocop-hq/rubocop/blob/a3ebf7188b545eeab54085ad0cfefc6f018e1a94/lib/rubocop/comment_config.rb#L13) or submit a PR to make it configurable. I'd probably say we should drop support for `rubocop:*` ones at the same time. Thoughts?

**Comment by searls** [comment]
Thanks, I love it

**Comment by searls** [comment]
Fixed by #186
