### ISSUE TITLE
Proposal: change Style/Alias to prefer_alias_method (or disable)

### ISSUE THREAD

**Issue by timriley** [testdouble/standard#185]
Hi @searls and fellow standardrb-ers,

I was porting a gem to standardrb today when I noticed it auto-corrected an `alias_method` to `alias`.

I note that the following rules are currently in place for `Style/Alias`:

```yml
Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias
```

Looking at the git blame for the `base.yml` file, it seems like this rule was never specifically tweaked, it was just brought in with the wholesale import of the original RuboCop defaults.

I would like to propose that we (a) change the enforced style to `prefer_alias_method`, or (b) disable the rule entirely.

As I was about to write my reasoning for this proposal, I actually found this recently opened issue on the Ruby Style Guide that sums up my thinking very well, so I'll point you to this first: https://github.com/rubocop-hq/ruby-style-guide/issues/821

Happy to discuss further, but I thought it'd be simplest just to point to that issue and gauge your feelings first.

Cheers!

**Comment by searls** [comment]
I'm willing to buy it. (Having used either method less than a dozen times in 15 years makes me easily swayed). Send a PR?

**Comment by timriley** [comment]
Thanks @searls! Will do 👍
