### ISSUE TITLE
Format on save for vscode?

### ISSUE THREAD

**Issue by iamajvillalobos** [testdouble/standard#187]
Hello, I'm loving standardrb since I love the opinionated config. But I'm looking on how to setup on vscode where when I save it, it runs `--fix` already. Is it possible at the current stage?

**Comment by searls** [comment]
Is this not covered by the existing extension? https://github.com/testdouble/standard/wiki/IDE:-vscode

There's at least one reference to it in the extension itself, so you may want to follow up there: https://github.com/testdouble/standard/wiki/IDE:-vscode
