### ISSUE TITLE
Autocorrect issue - parentheses removed and methods combined

### ISSUE THREAD

**Issue by sethherr** [testdouble/standard#192]
I just ran into an issue with autocorrect (for some ambiguous parentheses). It took this code:

```ruby
entry.author do |author|
  author.name (blog.user.name)
end
```

And converted it to:

```ruby
entry.author do |author|
  author.nameblog.user.name
end
```

...which doesn't work. It should have switched it to `author.name(blog.user.name)`

I'm not sure this is an issue with standard or if it should be addressed in rubocop

**Comment by jmkoni** [comment]
This should have been fixed with 0.90
