### ISSUE TITLE
Differing Behavior between TravisCI and local

### ISSUE THREAD

**Issue by thetizzo** [testdouble/standard#197]
Hi,

I'm experiencing an interesting issue with a gem of mine that is using Standard.  When I run Standard on my local machine, Standard passes with no offenses but when I run the exact same thing on CI then it fails.

The rules in question are `Style/TrailingCommaInHashLiteral`, `Style/TrailingCommaInArrayLiteral`, `Style/TrailingCommaInArguments`.

[Here is the CI build](https://travis-ci.com/github/thetizzo/nfl_data/jobs/379767323).  The errors on CI are all some version of `Avoid comma after the last item` but if I remove these trailing commas to get CI to pass then locally I see errors like this:

```
spec/api/player_spec.rb:18:13: C: Style/TrailingCommaInHashLiteral: Put a comma after the last item of a multiline hash.
            "image_source": "google.com"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/api/player_spec.rb:19:11: C: Style/TrailingCommaInArrayLiteral: Put a comma after the last item of a multiline array.
          }
```

My `.standard.yml` file is very simple:
```yml
parallel: true
format: progress
```

I have looked everywhere for any other conflicting config locally but I have nothing else for `rubocop` or `standard`.

**Comment by searls** [comment]
Since we swapped this setting at some point, all I can imagine is that your local version and travis's version of the gem differ. Can you provide a code sample and also the version read out (`standardrb -v`) in each environment?

**Comment by thetizzo** [comment]
Well differing versions was exactly the issue. 🤦  

My gemspec had "~> 0.1" which was using a `0.1.7` version I had installed locally but of course CI was installing the very latest `0.5.2`.  I thought I had run a bundle update locally but clearly I had not. 

Thanks for the quick response and sorry for the noise!  👋 😄

![](https://media1.tenor.com/images/9e9fdd1ebe593f3adf24b829a0f5a989/tenor.gif?itemid=3377649)
