### ISSUE TITLE
Using the `--fix` option with `--stdin` appends file content to the json result 

### ISSUE THREAD

**Issue by jgiovaresco** [testdouble/standard#199]
When I run the following commands `standardrb --format json --force-exclusion --stdin application_controller.rb < app/controllers/application_controller.rb`, I can see the result

```
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.0","ruby_patchlevel":"0","ruby_platform":"x86_64-darwin19"},"files":[{"path":"Gemfile","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}% 
```

However when I run `standardrb --format json --force-exclusion --fix --stdin Gemfile < app/controllers/application_controller.rb`, I have the result

```
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.0","ruby_patchlevel":"0","ruby_platform":"x86_64-darwin19"},"files":[{"path":"Gemfile","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}====================
class ApplicationController < ActionController::API
end
```

As you can see, the content of the linted file is appended to the JSON result.

This prevent tools (like RubyMine) to parse the response (https://youtrack.jetbrains.com/issue/RUBY-27006)

**Comment by jmkoni** [comment]
I was able to replicate this issue with a project I have. I also tried running the same command with rubocop and this seems to be an issue with rubocop that is filtering up to standard:
```
rubocop --format json --force-exclusion --fix --stdin application_controller.rb < app/controllers/application_controller.rb
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.1","ruby_patchlevel":"83","ruby_platform":"x86_64-darwin19"},"files":[{"path":"application_controller.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}====================
class ApplicationController < ActionController::Base
```

**Comment by jmkoni** [comment]
@jgiovaresco Since this is a rubocop bug, I would recommend opening up an issue in rubocop

**Comment by jgiovaresco** [comment]
Done: https://github.com/rubocop-hq/rubocop/issues/8673

**Comment by jmkoni** [comment]
@jgiovaresco I'm watching that issue now. Thanks for creating it 😄
