### ISSUE TITLE
Should substitutions for procedural blocks add whitespace? 

### ISSUE THREAD

**Issue by larquin** [testdouble/standard#2]
Adding standard to a gem I'm building, I ran `bundle exec standard --fix` and my default Gemfile was changed from: 
`git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }`

to: 

`git_source(:github) do |repo_name| "https://github.com/#{repo_name}" end`

Would we expect standard to decipher or try to determine white space there?

**Comment by larquin** [comment]
Interesting, good to know. I wonder if I can dig in and figure out how to exclude one liners.

**Comment by searls** [comment]
Shipped a fix for this in 0.0.5. You can see this cop for reference: https://github.com/testdouble/standard/blob/master/lib/standard/cop/semantic_blocks.rb
