### ISSUE TITLE
standard:fix creates begin..rescue..end syntax error

### ISSUE THREAD

**Issue by mperham** [testdouble/standard#205]
Hey standard team, I'm weeding the dalli gem and trying to get its codebase up to snuff by calling `standard:fix`. Everything works flawlessly save for one method:

**Before**

```ruby
    def groups_for_keys(*keys)
      groups = mapped_keys(keys).flatten.group_by do |key|
        begin
          ring.server_for_key(key)
        rescue Dalli::RingError
          Dalli.logger.debug { "unable to get key #{key}" }
          nil
        end
      end
      return groups
    end
```

**After**

```ruby
    def groups_for_keys(*keys)
      groups = mapped_keys(keys).flatten.group_by { |key|
        
          ring.server_for_key(key)
        rescue Dalli::RingError
          Dalli.logger.debug { "unable to get key #{key}" }
          nil
        
      }
      groups
    end
```

This results in a syntax error.

```
/Users/mikeperham/src/dalli/lib/dalli.rb:4:in `require': /Users/mikeperham/src/dalli/lib/dalli/client.rb:290: syntax error, unexpected `rescue', expecting '}' (SyntaxError)
        rescue Dalli::RingError
        ^~~~~~
/Users/mikeperham/src/dalli/lib/dalli/client.rb:294: syntax error, unexpected '}', expecting `end'
      }
      ^
rake aborted!
```

```
Using rubocop 0.92.0
Using rubocop-performance 1.8.1
Using standard 0.7
```

**Comment by searls** [comment]
Good catch! I suspect this is the fault of our only in-house rule [SemanticBlocks](https://github.com/testdouble/standard/blob/master/lib/standard/cop/semantic_blocks.rb).

Could you try manually writing `group_by` with `{` and `}`, fixing the begin/rescue/end by hand, and verifying it doesn't continue to break itself on `--fix`?

**Comment by mperham** [comment]
Yes, if I add the begin/end myself, it works fine.

**Comment by gavvvr** [comment]
Isn't it related to rubocop-hq/rubocop#7836 ?
The following `.rubocop.yml` will lead to the same problem after executing `rubocop -a`

```yaml
Style/BlockDelimiters:
  EnforcedStyle: semantic
```

My sample code I wanted to post before finding this issue:

```ruby
class Processor
  def handle_message(msg)
    pid = fork do
      puts "Processing message #{msg['id']}"
      raise 'Oops'
    rescue StandardError => e
      puts e.message
    ensure
      puts 'Cleaning up'
    end
    Process.detach(pid)
  end
end

Processor.new.handle_message({ id: 1 })
```

**Comment by searls** [comment]
Interesting! It might be the case that we could incorporate the (unmerged) patch here: https://github.com/tejasbubane/rubocop/commit/d3e5f63e87ae505eed8af69249b98f456687c3a7

Into our own SemanticBlocks cop (which we forked and which lives in this repo)
