### ISSUE TITLE
Performance/Sum should be removed or should not be Autocorrect: true because it is not type-safe

### ISSUE THREAD

**Issue by drbrain** [testdouble/standard#208]
In some of our code read docker-compose style durations like `1h30m` and we convert these to a single-unit duration.  A value must be valid and present and the conversion method enforces this.

During this conversion we want to reject an invalid unit, like `5n` (instead of `5m`).  Our lookup table returns `nil` for an invalid unit and attempts a multiplication which raises TypeError which we covert to an invalid duration.

If we have no units at all we depend on `Array#reduce(&:+)` on an empty Array to return `nil`, then pass that `nil` to Kernel#Integer which will raise TypeError, indicating an invalid (missing) duration.

As of this writing [autocorrect is enabled](/testdouble/standard/blob/c392b209d20aa77855e6df9f1e8c5d7b6fc85ede/config/base.yml#L706) in standard for Performance/Sum which changes the types for this method in an unsafe manner.  Instead of returning `nil` like `[].reduce(&:+)` which raises TypeError we get `0` from '[].sum` which Kernel#Integer does not raise a TypeError for.

Fortunately we have adequate tests to detect the type error that the suggestion introduced.

A performance improvement that introduces a bug is neither of those two things.

**Comment by drbrain** [comment]
See also rubocop-hq/rubocop-performance#177

**Comment by jmkoni** [comment]
Yeah, this rule also just isn't even working as intended so that + this issue and I think we'll just remove it 😂
