### ISSUE TITLE
standardrb compatibility with rubocop?

### ISSUE THREAD

**Issue by skatkov** [testdouble/standard#211]
I remember that standard could be used as a configuration base for rubocop before. But these days, while going through README and documentation there is basically zero mentions about this option (and only note about base file).

Here is a configuration I found from "back in the days":
```
require:
  # Performance cops are bundled with Standard
  - rubocop-performance
  # Standard's config uses this custom cop,
  # so it must be loaded
  - standard/cop/semantic_blocks
  
inherit_gem:
  standard: config/base.yml
```

I tried using a similar configuration in a new project and it lead to all sort of surprising issues.

What is the current stance on this? Does standard still support this use-case, or we should just copy base configuration to the project and not use standard gem in our bundle?

**Comment by searls** [comment]
We've never tried this or support it, because the point of Standard is that it not be configurable. I know some people have reported doing this with varying degrees of success (and more power to them!), but we're not considering making this work part of the project's purview
