### ISSUE TITLE
Make Style/MethodDefParentheses enabled by default

### ISSUE THREAD

**Issue by Gee-Bee** [testdouble/standard#213]
I've run tests on usage parentheses around parameters in method definitions.

**1)** test counted methods defined **with parenthesis** around parameters.
```shell
ag --stats '^[ \t]*def +(?=.*\()'
```

**2)** test counted methods defined **without parenthesis** around parameters.
```shell
ag --stats '^[ \t]*def(?: +[^ \n#<;\(]+){2,}'
```
The results are unambiguous:

| | 1) with | 2) without |
| --- | --- | --- |
| [rails](https://github.com/rails/rails) | 9171 | 1 |
| [devise](https://github.com/heartcombo/devise) | 292 | 1 |
| [rubocop](https://github.com/rubocop-hq/rubocop) | 4297 | 45 |
| [puma](https://github.com/puma/puma) | 4392 | 45 |

If it's not possible to enable this by default, is it possible to add this rule manually to config file?

**Comment by searls** [comment]
What do you mean to say is unambiguous about the results? That those projects use parentheses in method definitions?

In any case, we're intentionally flexible about enforcing whether method defs and invocations use parentheses, because we want to be [inclusive of Rubyists from Seattle](https://whydavewhy.com/2013/09/05/parentheses-in-ruby/comment-page-1/)

But in all seriousness, this isn't something that I think Standard should be in the business of constraining people on. The freedom to express yourself with a bare minimum of supporting syntax is one of Ruby's strengths, and tamping that down just for the sake of uniformity would be a real shame.

**Comment by Gee-Bee** [comment]
> What do you mean to say is unambiguous about the results? That those projects use parentheses in method definitions?

Yes, that's exactly what I meant.

> In any case, we're intentionally flexible about enforcing whether method defs and invocations use parentheses, because we want to be [inclusive of Rubyists from Seattle](https://whydavewhy.com/2013/09/05/parentheses-in-ruby/comment-page-1/)

That's right. When comparing minitest and flog, the results where quite the opposite to the ones from the table. 
If I would take them under consideration, the results in the table would be ambiguous ;)

> But in all seriousness, this isn't something that I think Standard should be in the business of constraining people on. The freedom to express yourself with a bare minimum of supporting syntax is one of Ruby's strengths, and tamping that down just for the sake of uniformity would be a real shame.

Understood. 
Talking about constaints and goind back to the question. Is it possible to enable this rule using standard gem on a project basis, or it's 'take it or leave it' scenario?

**Comment by jmkoni** [comment]
You can if you do something like this and use standard rules, but use rubocop instead: https://github.com/testdouble/standard/issues/158#issuecomment-640118656

**Comment by Gee-Bee** [comment]
> You can if you do something like this and use standard rules, but use rubocop instead: [#158 (comment)](https://github.com/testdouble/standard/issues/158#issuecomment-640118656)

Thank you for pointing that. Works like a charm :tada: 

For anyone who stumbled this:
- install `standard` as regular - `rubocop` is listed as dependency,
- use `rubocop` for formatting and linting,
- put this in your `.rubocop.yml`:
```yaml
require:
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
```
