### ISSUE TITLE
How to use other pluggable Cops?

### ISSUE THREAD

**Issue by gavvvr** [testdouble/standard#215]
I.e I would like to get suggestions from `rubocop-rspec` right in my IDE.
WIth Rubocop I would simply append to `.rubocop.yml`:

```yaml
require:
  - rubocop-rspec
```

How to add pluggable Cops with `standardrb`?

UPD: Just realized this is a duplicate of #135. Actually I [came up](https://gist.github.com/gavvvr/5873313c6a87ba1d32ea31920d0557f4) to [the same solution](https://github.com/testdouble/standard/issues/135#issuecomment-651198150)  and was wondering if there is a more correct way

**Comment by searls** [comment]
No, that workaround is probably your best bet. Sorry, we so far haven't considered a way to add official/built-in support for this kind of thing without opening the door to all rule customizations, defeating the purpose of the tool
