### ISSUE TITLE
Update `Layout/HashAlignment` to use `ignore_implicit`

### ISSUE THREAD

**Issue by jmkoni** [testdouble/standard#216]
Right now, if key value pairs are sent as arguments, we are reading it as a hash, not arguments, and treating it as such. That means we get formatting like this:

```
update(foo: bar,
       baz: boo,
       pony: party)
```
when what we want is:

```
update(foo: bar,
  baz: boo,
  pony: party
)
```

**Comment by jmkoni** [comment]
Ok, maybe not. I changed this setting and these were the results:
in autocorrectable-bad, I added:
```
do_stuff(a: 1,
                     b: 2,
                     c: 3
                    )
```
which corrected to:
```
    do_stuff(a: 1,
                       b: 2,
                       c: 3)
```
which is not ideal.
Then this one also didn't get corrected anymore:
```
config.fog_credentials_as_kwargs(
      provider:              "AWS",
      aws_access_key_id:     ENV["S3_ACCESS_KEY"],
      aws_secret_access_key: ENV["S3_SECRET"],
      region:                ENV["S3_REGION"]
    )
```

I think we'd need a new rubocop option in order to fully fix this. TBD on what that should be.

**Comment by jmkoni** [comment]
Gonna unassign this in case someone else feels like taking this on in the meantime :)

**Comment by koic** [comment]
This looks like a false negative for `Layout/ArgumentAlignment`. I've opened rubocop/rubocop#9798.

**Comment by searls** [comment]
And it's already merged! You're amazing, @koic!
