### ISSUE TITLE
Add UnusedMethodArgument to config.

### ISSUE THREAD

**Issue by thijsnado** [testdouble/standard#217]
This is a handy lint rule that catches when you forget to use an argument you passed in a function. See https://docs.rubocop.org/rubocop/1.1/cops_lint.html#lintunusedmethodargument for documentation. Only down side I can see is sometimes you need un-used arguments for duck typing or Liskov Substitution Principle conformance.

**Comment by jmkoni** [comment]
This seems like a good idea to me. Not sure if there was a reason in the past for not adding it. I'm guessing it might have been because `IgnoreEmptyMethods: true` and `IgnoreNotImplementedMethods: true` maybe weren't enabled?

**Comment by jmkoni** [comment]
Ok, we decided against it because duck typing is too important to Ruby.

**Comment by thijsnado** [comment]
I think for ordered arguments, using the underscore prefix works (`_unused_arg`) for preserving duck type. For kwargs it's a tad harder but in theory you can do:

```ruby
class AClass
  def method(used:, also_used:)
    puts used
    puts also_used
  end
end

class ADuckClass
  def method(used:, **_unused)
    puts used
  end
end
```

I don't think it would work if you did more advanced reflection on methods but for average use case perhaps that is a good enough workaround to allow the rule?
