### ISSUE TITLE
frozen_string_literal

### ISSUE THREAD

**Issue by jnicklas** [testdouble/standard#22]
Just ran this on a project, and the majority of changes I can live with, one thing that I didn't agree with was that that `frozen_string_literal` magic comments were stripped. I can totally see this thing taking a neutral attitude on `frozen_string_literal`, but if they're already there it should probably leave them alone?

We did see rather substantial memory savings due to adding the frozen string command. I'm aware that there is a flag you can set to freeze all string literals, but this is problematic because flags are non-local, and also it can be a fiddly to ensure that the flag is always set, both in dev/test/ci/production.

**Comment by elia** [comment]
Also we're in the midst of a transition toward frozen strings by default in Ruby 3.0, until then it's should be allowed to keep them. 

https://twitter.com/yukihiro_matz/status/634386185507311616
https://bugs.ruby-lang.org/issues/11473

**Comment by searls** [comment]
Yes, absolutely agree. This is an oversight

**Comment by searls** [comment]
Landed in 0.0.11
