### ISSUE TITLE
Consider disabling Style/EmptyCaseCondition

### ISSUE THREAD

**Issue by aliismayilov** [testdouble/standard#229]
I don't find either of following code snippets to be better than the other:
```ruby
case
when done?       then :done
when exception?  then :exception
else :processing
end
```

```ruby
if done?
  :done
elsif exception?
  :exception
else
  :processing
end
```

in fact, me and colleagues use the first example more often. 

original discussion: https://github.com/rubocop-hq/rubocop/issues/3019

**Comment by searls** [comment]
I appreciate the spirit of this and I'm always open to cases where keywords like `case` can improve expressiveness, but I think this rule is a good one and it's going to stay. Reason being: many developers don't know what an empty `case` statement will do (I didn't until reading this issue, and I've been using Ruby for a while now), and reducing ambiguity in what a program will do at runtime has some value when we decide which rules are net-beneficial. Closing for now but will gladly welcome others' opinions in the comments

**Comment by aliismayilov** [comment]
> I appreciate the spirit of this and I'm always open to cases where keywords like `case` can improve expressiveness, but I think this rule is �a good one and it's going to stay. Reason being: many developers don't know what an empty `case` statement will do (I didn't until reading this issue, and I've been using Ruby for a while now), and reducing ambiguity in what a program will do ��at� r���untime has some value when we decide which rules are net-beneficial. Closing for now but will gladly welcome others' opinions in the comments

Thanks for clarification! I see your point, but I'd like to then ask, wouldn't the same argument (many developers don't know how case statement works) apply in the following example too?

```ruby
case string
when "foo" then puts "hi!"
when /^foo.*/ then puts "ho!"
end
```

This might not be the best example, but my point is that it's possible that multiple when conditions can match the variable, but only the first matching one will be executed. This was never confusing [to me], as I've never seen `break` statements inside case statements in Ruby (and I love this cleanliness). With Ruby's new pattern matching inside case statements might introduce more of these situations, where multiple when conditions might match and developers should know how this works.

I hope, I could explain myself, as with the above example, the standard gem will be happy, but the developers who don't know how case statements work in Ruby will still be confused.

**Comment by twe4ked** [comment]
I often use empty `case` statements over `if`/`elsif` when there are more than 2-3 options. I find it makes it clearer when the branches aren't different importances.

**Comment by nilcolor** [comment]
Also, `if`s kind of imply hierarchy (imo). While `case`s is kind of "decision point" with all options to be on the same level of importance... (imo again). Hence
```ruby
case # rubocop:disable Style/EmptyCaseCondition
when search_term then by_term
...
```
is kind of common in our code base :) (yeah, this can be disabled but still doesn't)

**Comment by ramhoj** [comment]
Thank you @searls. I've submitted a #787 for your consideration.
