### ISSUE TITLE
Style/TrailingUnderscoreVariable looks like a bug, or it's too CLEVER

### ISSUE THREAD

**Issue by elia** [testdouble/standard#23]
`Style/TrailingUnderscoreVariable` will "fix" this:

```rb
inner, _ = *node
```

into this:

```rb
inner, = *node
```

The latter looks very hackish, almost a glitch, whereas the explicit ignored param tells a better story.

**Comment by searls** [comment]
:100: agree

**Comment by searls** [comment]
Landed in 0.0.11
