### ISSUE TITLE
Consider selecting the rules to enable instead of disabling unwanted ones

### ISSUE THREAD

**Issue by elia** [testdouble/standard#24]
Starting with everything disabled would ensure that:
- everything that makes the list is properly vetted
- (probably) keeps the list shorter
- avoids weird/little-known rules to popup
- assumes trust and openness toward people's code

**Comment by stevenjackson** [comment]
This would be onerous right now, but would probably pay off the first time a rubocop minor upgrade adds default rules that standard users disagree with.

**Comment by searls** [comment]
Firm :+1:. This was raised by @mame & @amatsuda on Twitter and I agree we should do this. I plan on dumping the current config this weekend and pruning it instead of hunting for exceptions as we have been.

**Comment by searls** [comment]
Thanks all! Landed in 0.0.12
