### ISSUE TITLE
False positive Standard/SemanticBlocks in method with rescue

### ISSUE THREAD

**Issue by matssigge** [testdouble/standard#246]
The following code is ok according to Standard.
```ruby
class Foo
  def foo
    [1, 2].map { |value|
      value.to_s
    }
  end
end
```

However, when adding a rescue clause to the method, Standard gives a `Standard/SemanticBlocks` warning, although the code hasn't actually changed semantics.
```ruby
class Foo
  def foo
    [1, 2].map { |value|
      value.to_s
    }
  rescue
    raise
  end
end
```

Chaining a method after the `map` removes the warning again, so my guess is it has something to do with the "offending" block being the last before the `rescue`.

**Comment by searls** [comment]
Seems related to #94 -- @jmkoni, thoughts?

**Comment by jmkoni** [comment]
@searls Yeah, it's hard to tell if it's the exact same issue or not. In #94, the rescue is within the braces vs here. But it does seem like we generally have a problem with rescuing within blocks (#94) and after blocked (like this example).
