### ISSUE TITLE
Errant semantic block cases around class mutation

### ISSUE THREAD

**Issue by dnsco** [testdouble/standard#248]
Given that the point of this block is to add a method to the struct, I think it should be do end.

```
ValueObject = Struct.new(:events) {
    def random_name
      @event_name ||= events.sample.name
    end
  }
```

I've also hit this issue a couple other times when doing metaprommey things.

**Comment by dnsco** [comment]
just saw #109

**Comment by jmkoni** [comment]
What we would recommend is the following:

```
class ValueObject < Struct.new(:events)
  def random_name
     @event_name ||= events.sample.name
  end
end
```
