### ISSUE TITLE
Enhance our CI build to run against multiple Rubies

### ISSUE THREAD

**Issue by searls** [testdouble/standard#249]
Because Standard is designed to run under whatever Rubies are supported by the version of rubocop we depend on and _against_ source listing compatibility all the way back to 1.8.7, I really would like to see our [GitHub Actions CI build](https://github.com/testdouble/standard/runs/1681563940) run with a few representative versions of MRI (perhaps oldest supported, most typical, and latest release)

Anyone familiar with using GitHub actions for Ruby CI interested in showing us how to set this up correctly?

**Comment by anoymouscoder** [comment]
At present, I have seen some ruby versions in the ci file https://github.com/testdouble/standard/blob/master/.github/workflows/test.yml#L12-L15.  Does this issue already resolved?

**Comment by searls** [comment]
Ah yep. I assumed the other PRs had marked themselves as resolving this one, thanks
