### ISSUE TITLE
Constants & trailing comma formatting issue

### ISSUE THREAD

**Issue by searls** [testdouble/standard#25]
Our combination of trailing comma + not forcing freeze is triggering a pretty nasty autocorrect bug: https://github.com/rubocop-hq/rubocop/issues/6498

**Comment by koic** [comment]
Hi @searls 👋 
https://github.com/rubocop-hq/rubocop/issues/6498 has been resolved.
It will be included in the next RuboCop release (> 0.74.0). Thank you for the feedback.

**Comment by searls** [comment]
Amazing, thank you @koic & RuboCop team! 🙏

**Comment by jmkoni** [comment]
Not sure when we did this release, but we have upgraded past 0.74 now 😅 so closing this issue.
