### ISSUE TITLE
Rubocop upset about BlockDelimiters change to config/base.yml

### ISSUE THREAD

**Issue by mepatterson** [testdouble/standard#271]
I had everything working great with Standard + Rubocop + Rails. In my `.rubocop.yml`, I have this:
```
inherit_gem:
  standard: config/base.yml
```

Now, after updating versions, rubocop is blowing up with:

```
...gems/standard-1.0.2/config/base.yml: Standard/BlockDelimiters has the wrong namespace - should be Style
```

I use overcommit, so this is suddenly preventing me from committing due to the pre-commit hook failure. I don't really know how to proceed. Any ideas?

**Comment by searls** [comment]
Hmm… sounds like it may be a bug in RuboCop. I suspect that RuboCop moved Style/BlockDelimiters from another section (Layout, maybe?) and as a result has migration warnings in there such that if a configuration contains a cop named BlockDelimiters in _any other_ section, it'll blow up and tell you to rename it

**Comment by searls** [comment]
Should be worked-around in 1.0.4

**Comment by swrobel** [comment]
Unfortunately I'm getting `Error: unrecognized cop Standard/BlockSingleLineBraces found in vendor/bundle/ruby/2.7.0/gems/standard-1.0.4/config/base.yml`

**Comment by searls** [comment]
@swrobel could you please explain how you're using Standard such that this error is being raised?

**Comment by swrobel** [comment]
Same way as the OP
