### ISSUE TITLE
Clarity required for a N00b

### ISSUE THREAD

**Issue by resistorsoftware** [testdouble/standard#274]
My home directory has a .rubocop.yml file that requires rubocop-rails. 

My code editor (VSCode) is tuned to lint with Rubocop. So when I add a .rubocop.yml to my actual Rails App codebase, I can override things, and linting is done. 

So now I add standard gem to my Rails App, bundle, and I have it. In my terminal I run standardrb and get the results. Fine. 

But it conflicts a lot with Rubocop cops. So let us assume I want to backoff using Rubocop Rails and let Standard run the show. I remove the two .rubocop.yml files, and Rubocop is then linting off of some internal defaults. No dependence on rubocop-rails. But for my 22 other Rails App not yet migrated to Standard, that missing .rubocop.yml in the home directory of the mothership is trouble... along with the fact my editor still explicitly lints with Rubocop. 

Can I remove VSCode linting with Rubocop and replace with Standard to get constant linting in code edit? 
Can I remove my .rubocop.yml files and just use gem standard? 

I am seeing conflicting styles at the moment, and I am not sure of the best approach to try standard without really axing everything. Any hot tips on how to maybe gently nurture myself into this?

**Comment by jmkoni** [comment]
This is not officially supported by standard, but this blog post that we link to in the readme should get you up and running: https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

We also have plans to add rubocop-rails in some way (still trying to figure that out) #266

**Comment by resistorsoftware** [comment]
Than you!
