### ISSUE TITLE
obj.instance_eval("SomeStrings") is not handled correctly

### ISSUE THREAD

**Issue by ngiger** [testdouble/standard#275]
File `test_eval.rb` looks like this
```ruby
def mytest
    xxx = String.new
    xxx.instance_eval('@additional_javascripts = additional_javascripts')
end
```
After running `bundle exec standardrb test_eval.rb --fix` it looks like this
```ruby
def mytest
  xxx = ""
    xxx.instance_eval("@additional_javascripts = additional_javascripts"), __FILE__, __LINE__
end
```
which is not correct

**Comment by koic** [comment]
Thank you for opening the issue. This is a RuboCop's bug and I opened https://github.com/rubocop/rubocop/pull/9616 to RuboCop core.
