### ISSUE TITLE
regex capture is fixed

### ISSUE THREAD

**Issue by michelson** [testdouble/standard#278]
Hello, I found a strange behavior on how standardRb is fixing regexes:

standardrb is changing the regex from this:
  `/(?i)support|soporte|[^(career)]\s?success|customer service/`
to this:
`  /(?i)support|soporte|[^(care)]\s?success|customer service/

**Comment by searls** [comment]
Aren't `[^(career)]` and `[^(care)]` equivalent character classes, though? Could you give an example of something matched by the first but not the second?

**Comment by michelson** [comment]
oh , sorry about this, you are right!
