### ISSUE TITLE
VSCode problems

### ISSUE THREAD

**Issue by resistorsoftware** [testdouble/standard#282]
I see this problem in my terminal. Not surw what the cause is. 

    cannot load such file -- standard/cop/semantic_blocks

    Request textDocument/rangeFormatting failed.
       Message: Request textDocument/rangeFormatting failed with message: 

Is there something simple I can do here to silence the error thrown by this?

**Comment by searls** [comment]
Standard no longer ships with a cop named SemanticBlocks -- perhaps the vscode extension needs to be updated?

**Comment by resistorsoftware** [comment]
I was not aware of VSCode having an extension. I am seeing this from the Ruby Linting being done in VSCode, which has been deferred to standard now that I have walked away from pure Rubocop. In other words:

    Format: executing bundle exec rubocop -s '/Users/beerme/Documents/Workspace/Apps/galugaadmin/app/controllers/api/beers_controller.rb' -a...
    Lint: executing bundle exec standardrb -s '/Users/beerme/Documents/Workspace/Apps/galugaadmin/app/controllers/api/beers_controller.rb' -f json --no-fix...
    cannot load such file -- standard/cop/semantic_blocks

**Comment by searls** [comment]
The [vscode-ruby](https://github.com/rubyide/vscode-ruby) has standard integration but I don't see any notes about version. I had assumed it'd use whatever the version in your project's gemfile.lock was https://github.com/testdouble/standard/wiki/IDE:-vscode

**Comment by resistorsoftware** [comment]
The terminal states my standard version being used is 

    /gems/ruby-2.7.2/gems/standard-1.0.4/lib/standard.rb

Not sure that contributes to any problems.
