### ISSUE TITLE
is .rubocop.yml ignored?

### ISSUE THREAD

**Issue by jjb** [testdouble/standard#286]
thanks for a great project!

is .rubocop.yml ignored? Seems like that would be a good idea and that it is, but just wanted to check. Perhaps good to mention in the Readme, I can make a PR.

**Comment by searls** [comment]
It is not ignored, but that's because it's not loaded or considered by the CLI. It's a separate project that happens to depend on rubocop's API under the hood. Projects can have both CLIs configured and in use side-by-side if they choose (whether that's a useful idea, I'm less sure!)
