### ISSUE TITLE
--fix indents a part of a hash in a *very* strange way

### ISSUE THREAD

**Issue by myronmarston** [testdouble/standard#293]
Given `standardrb_bug.rb` with:

``` ruby
hash1 = {
  bool: {should: [
    {
      bool: {
        filter: [
          {terms: {"transaction_type" => ["CARD"]}}
        ],
        should: [
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 10000}}}
          ]}},
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 1000}}},
            {term: {"total_amount.currency" => "USD"}}
          ]}}
        ],
        minimum_should_match: 1
      }
    },
    {
      bool: {filter: [
        {terms: {"transaction_type" => ["CASH"]}}
      ]}
    }
  ],
  minimum_should_match: 1}
}

do_something_with(hash1)

do_something(aggregations:
  [
    agg_clause(:sum, "amount_cents"),
    agg_clause(:avg, "amount_cents"),
    agg_clause(:min, "amount_cents"),
    agg_clause(:max, "amount_cents")
  ].reduce(:merge),
  total_document_count_needed: true
)
```

...when I run the following:

```
$ standardrb --version
1.1.1
$ standardrb standardrb_bug.rb --fix
```

...it changes the source file to:

``` ruby
hash1 = {
  bool: {should: [
    {
      bool: {
        filter: [
          {terms: {"transaction_type" => ["CARD"]}}
        ],
        should: [
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 10000}}}
          ]}},
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 1000}}},
            {term: {"total_amount.currency" => "USD"}}
          ]}}
        ],
        minimum_should_match: 1
      }
    },
    {
      bool: {filter: [
        {terms: {"transaction_type" => ["CASH"]}}
      ]}
    }
  ],
         minimum_should_match: 1}
}

do_something_with(hash1)

do_something(aggregations:
  [
    agg_clause(:sum, "amount_cents"),
    agg_clause(:avg, "amount_cents"),
    agg_clause(:min, "amount_cents"),
    agg_clause(:max, "amount_cents")
  ].reduce(:merge),
             total_document_count_needed: true)
```

Note that it makes `minimum_should_match: 1` and `total_document_count_needed: true` float over with very strange indentation.  The prior formatting wasn't necessarily great, but having weird floating parts of these hashes seems much worse.

**Comment by searls** [comment]
Totally agreed, surely we're doing something wrong in how we're configuring keyword alignment (maybe that counts as the implicit side of [Layout/HashAlignment](https://www.rubydoc.info/gems/rubocop/0.83.0/RuboCop/Cop/Layout/HashAlignment)

**Comment by jmkoni** [comment]
Doing some testing... when I change `EnforcedLastArgumentHashStyle` from `always_inspect` to  `ignore_implicit`, that fixes the issue with `total_document_count_needed`, but `minimum_should_match` is still hanging out in the ether...

```
hash1 = {
  bool: {should: [
    {
      bool: {
        filter: [
          {terms: {"transaction_type" => ["CARD"]}}
        ],
        should: [
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 10000}}}
          ]}},
          {bool: {filter: [
            {range: {"total_amount.amount" => {gt: 1000}}},
            {term: {"total_amount.currency" => "USD"}}
          ]}}
        ],
        minimum_should_match: 1
      }
    },
    {
      bool: {filter: [
        {terms: {"transaction_type" => ["CASH"]}}
      ]}
    }
  ],
  minimum_should_match: 1}
}

do_something_with(hash1)

do_something(aggregations:
  [
    agg_clause(:sum, "amount_cents"),
    agg_clause(:avg, "amount_cents"),
    agg_clause(:min, "amount_cents"),
    agg_clause(:max, "amount_cents")
  ].reduce(:merge),
  total_document_count_needed: true
)
```

**Comment by jmkoni** [comment]
Ok, this still isn't *perfect*, but it looks like if you move `should: [` to the next line, it indents correctly. What it's doing now is lining up that last `minimum_should_match` with `should`. If you simplify this a lot, this code:
```
   1   │ hash1 = {
   2   │   bool: {should: [],
   3   │     minimum_should_match: 1
   4   │   }
   5   │ }
   ```
  corrects to this:
  ```
   1   │ hash1 = {
   2   │   bool: {should: [],
   3   │          minimum_should_match: 1}
   4   │ }
   ```
   which I'm not entirely sure is wrong. We might want to consider if `should` should be forced to be on the next line, but I think this is correcting correctly.

**Comment by searls** [comment]
> which I'm not entirely sure is wrong. We might want to consider if should should be forced to be on the next line, but I think this is correcting correctly.

At the very least, I could see arguments on both sides for that behavior, at least when it comes to hash/array literals. 

For multi-line invocations, I'd definitely prefer not trying to align the arguments at all. For example, I'd like to see standard push towards these:

```ruby
# good
throw_a_party(:birthday,
  foods: [:cake, :pizza]
)

# good
throw_a_party(type: :birthday,
  foods: [:cake, :pizza]
)
```

Reason being that a lot of times the first argument is a modifier on the method (almost like an adverb), whereas subsequent arguments are more of a data payload that actually need multiple lines (and max available indentation space) to breathe. It'd be a shame if the above were ever corrected to 

```ruby
# bad
throw_a_party(:birthday,
                          foods: [:cake, :pizza])

# bad
throw_a_party(type: :birthday,
                          foods: [:cake, :pizza])
```

**Comment by jmkoni** [comment]
@searls with the current set of rules, the code you provided just gets corrected to:
```
   6   │ # good
   7   │ throw_a_party(:birthday,
   8   │   foods: [:cake, :pizza])
   9   │
  10   │ # good
  11   │ throw_a_party(type: :birthday,
  12   │   foods: [:cake, :pizza])
  ```
  So it's just moving that last paren inline. Does this seem correct to you?

**Comment by jmkoni** [comment]
Alright, I think we are good here. @myronmarston feel free to reopen if you have further comments on this issue.
