### ISSUE TITLE
Is there a way to drop all the equal signs you get when you use stdin?

### ISSUE THREAD

**Issue by will** [testdouble/standard#313]
I think it's coming from rubocop, but I haven't been able to find any options there that get rid of this.

```
/tmp> cat a.rb
def foo
hello = 3
4
end

/tmp> cat a.rb | standardrb --fix-layout -s --
====================
def foo
  hello = 3
  4
end
```

I'm trying to hook this into a new neovim 0.5 fixer (without ale). Ale [does some post processing](https://github.com/dense-analysis/ale/blob/f0887d3e6178482255f11aa378124aef3699245f/autoload/ale/fixers/rubocop.vim#L5-L7) to get rid of this, but it'd maybe be easier if there was a flag or something to get _only_ the formatted output? I might just be missing it form the rubocop help though.

**Comment by will** [comment]
Ah, well I figured to send it through awk

``` lua
lang.ruby.formatter = {
  exe = "standardrb",
  args = { '--fix', '--stdin', '%:p', '2>/dev/null', '|', "awk 'f; /^====================$/{f=1}'" },
  stdin = true,
}
```

not like super pretty, but does the job. Putting it here in case others come across it.

**Comment by searls** [comment]
cc/@koic - Do you know of a formatter in rubocop that might accomplish what Will wanted?

**Comment by will** [comment]
I've now solved this a completely different way, by[ hacking standard as a formatter into Solargraph](https://github.com/castwide/solargraph/issues/466), which I _think_ is faster since you don’t have to pay the ruby startup time on each format and lint. It feels faster at least.

**Comment by searls** [comment]
Hey @will this is super cool! I'd somehow never seen Solargraph before, but I'd love to try it for this purpose -- were they open to considering a PR based on your monkey patch?

**Comment by will** [comment]
Yeah, looks like it might be pretty soon hopefully:

> Setting formatters from plugins is on the roadmap. Thanks for the example implementation. This feature is long overdue, so I'll try to get it into the next minor release.

And it's working pretty well so far!

https://user-images.githubusercontent.com/1973/127191212-e4c3575c-9a48-4bc3-a6e1-ea35ff9d0c48.mov

**Comment by searls** [comment]
That's great to hear! If you wouldn't mind keeping us in mind if/when this ships so we can add some basic instructions for getting started with standard + solargraph, I'd really appreciate it
