### ISSUE TITLE
Unclear if it uses existing RuboCop configs

### ISSUE THREAD

**Issue by vassilevsky** [testdouble/standard#314]
Hello :)

Could you add to the README information about existing RuboCop configuration files?

I believe many developers who are looking into Standard are already using RuboCop and have the following configuration files at the root of the project:

    .rubocop.yml
    .rubocop_todo.yml

How do they affect the behaviour of Standard?
Should I delete them before running Standard?

It would be great to have this info in the README.

Thanks!

**Comment by searls** [comment]
Since it's a rubocop feature, those files only interact with rubocop's CLI. Our readme covers analogous but not compatible files: `.standard.yml` and `.standard_todo.yml`
