### ISSUE TITLE
Style/TrivialAccessors is a little heavy handed for class methods

### ISSUE THREAD

**Issue by searls** [testdouble/standard#316]
Given:

```ruby
  def self.refresh_materialized_view
    @refresh_materialized_view_count ||= 0
    execute "refresh materialized view meta_boops"
    @refresh_materialized_view_count += 1
  end

  def self.refresh_materialized_view_count
    @refresh_materialized_view_count
  end
```

The second method will error with "Style/TrivialAccessors: Use `attr_reader` to define trivial reader methods."

This would be fine, except the autocorrect really feels overkill since it also breaks the symmetry of these two methods:

```ruby
  def self.refresh_materialized_view
    @refresh_materialized_view_count ||= 0
    execute "refresh materialized view meta_boops"
    @refresh_materialized_view_count += 1
  end

  class << self
    attr_reader :refresh_materialized_view_count
  end
```

**Comment by camilopayan** [comment]
I don't think there's a way out of that, unfortunately, without writing our own version of this rule.

https://docs.rubocop.org/rubocop/cops_style.html#ignoreclassmethods-false-default

I guess it'd be preferable to only have

```ruby
attr_reader :refresh_materialized_view_count
```

in this case?

**Comment by searls** [comment]
Yeah, since the class method path for this has the broader-than-maybe-intended effect of doing the `class << self` shuffle, I think we should set `IgnoreClassMethods: true`
