### ISSUE TITLE
advice: vim ale

### ISSUE THREAD

**Issue by will** [testdouble/standard#32]
Not sure if an issue is the best place to ask, but does anyone have advice on how to hook this up with https://github.com/w0rp/ale ? It already has support for rubocop, so I imagine it's doable, but I'm bad at vimscript :(

**Comment by rosston** [comment]
I haven't tested it, but `*ale-integrations-local-executables*` in [ALE's vim doc](https://github.com/w0rp/ale/blob/0a384a49d371838903d8401c5358ec60f3f4266d/doc/ale.txt) points a way forward for a short-term fix. I think you could do this in your vimrc:
```vim
let g:ale_ruby_rubocop_executable = 'standardrb'
```

**Comment by will** [comment]
Thanks @rosston, that worked!
