### ISSUE TITLE
Disable Style/CommentedKeyword

### ISSUE THREAD

**Issue by searls** [testdouble/standard#326]
[Style/CommentedKeyword](https://docs.rubocop.org/rubocop/cops_style.html#stylecommentedkeyword) is a weird one, but I just got bit by it and it felt like Standard was overreaching.

Was writing a chaining method:

```ruby
def start(&blk) # .then()
end
```

With the comment to indicate the next method in the chain to the reader. @camilopayan?

**Comment by camilopayan** [comment]
Yea I think we should leave that one out. Comments are up to the writer imo.
