### ISSUE TITLE
Add Layout::EmptyLineAfterGuardClause for improved readability

### ISSUE THREAD

**Issue by mrbongiolo** [testdouble/standard#327]
Not sure if this is the correct place to make a suggestion, but it would be good to have `RuboCop::Cop::Layout::EmptyLineAfterGuardClause` enabled. 
Personally, I've always favored empty lines for code organization and context management, this rule helps with code readability as it makes it clearer which lines or "blocks" are "breaking" earlier.

Examples from Rubocop docs:
```ruby
# bad
def foo
  return if need_return?
  bar
end

# good
def foo
  return if need_return?

  bar
end

# good
def foo
  return if something?
  return if something_different?

  bar
end

# also good
def foo
  if something?
    do_something
    return if need_return?
  end
end
```

**Comment by searls** [comment]
I personally do this in my code, but I think whether a guard clause counts as a guard clause is a semantic difference that looks and feels a lot different based on context, intent, method length, etc., so I'd prefer we don't enforce it one way or another
