### ISSUE TITLE
Ignored files are not ignored when passed as CLI arguments

### ISSUE THREAD

**Issue by juanmanuelramallo** [testdouble/standard#354]
## Steps to reproduce
1. Have a config file that looks like this:
```yml
# .standard.yml
ignore:
  - 'db/schema.rb'
```
2. Execute:
```bash
bundle exec standardrb db/schema.rb
```
## Expected
db/schema.rb is ignored

## Actual
db/schema.rb is processed

## Rationale
Large codebases usually execute their linters against a subset of files from the codebase, the files that changed in the last commit, therefore it's useful to pass the list of changed files to standardrb via the command line. A simple bash command to perform this would look like the following script:
```bash
git diff --cached --name-only --diff-filter=AMR |
  egrep '\.rb$|\.rake$' |
  xargs bundle exec standardrb
```

# Solved

@grosser suggested to use `--force-exclusion` when executing standard so that configured exclusions are taken into account despite of the CLI arguments (https://docs.rubocop.org/rubocop/configuration.html#includingexcluding-files)

Updating the previous example script:
```bash
git diff --cached --name-only --diff-filter=AMR |
  egrep '\.rb$|\.rake$' |
  xargs bundle exec standardrb --force-exclusion
```

**Comment by searls** [comment]
Great issue, thanks for explaining this. I understand what you're saying and agree that this should work.

**Comment by grosser** [comment]
@juanmanuelramallo does https://github.com/testdouble/standard/pull/335 solve your issue ?

**Comment by juanmanuelramallo** [comment]
@grosser Seems like it does not :( 

After cloning and checkouting your branch, I did the following:

```ruby
# Gemfile
gem "standard", github: "testdouble/standard", branch: "grosser/exclude"
```
```
$ bundle config set local.standard ~/oss/standard/
```
```
$ bundle install
[...]
Using standard 1.4.0 (was 1.1.2) from https://github.com/testdouble/standard.git (at ~/oss/standard@463691e)
[...]
```
Updated standard.yml to ignore the db/schema.rb
```yml
ignore:
  - 'db/schema.rb'
```
```
$ bundle exec standardrb db/schema.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `standardrb --fix` to automatically fix some problems.
  db/schema.rb:14:1: Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.
```
It is not ignored.

**Comment by grosser** [comment]
thx for trying, I'll see if it's an easy fix or maybe I got something wrong in the PR
FYI `bundle config set local.standard ~/oss/standard/` should not be needed

**Comment by juanmanuelramallo** [comment]
Yeah it's just so that it uses my local repository. I couldn't make the remote one to work with your branch, perhaps branches from forks are not allowed there.

**Comment by grosser** [comment]
yeah this is a rubocop issue 😞 
```
rubocop vendor/foo.rb
Inspecting 1 file
C

Offenses:

vendor/foo.rb:1:1: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
'hi'
^^^^
```

**Comment by grosser** [comment]
needs `--force-exclusion`

**Comment by juanmanuelramallo** [comment]
`--force-exclusion` works like a charm 

Thank you for the exploration! I wasn't aware of that flag, and it seems like it solves this issue completely
