### ISSUE TITLE
enforce %w instead of %W

### ISSUE THREAD

**Issue by will** [testdouble/standard#355]
Just had a pr come in where someone new to ruby used a capital `W` for an array literal. I didn't even know that was a thing. I looked around docs to see if it was something like `%q` vs `%Q`, but as far as I can tell there is no difference.

Can standard correct and/or enforce just lowercase w for string array literals? I'm not sure if there is a rubocop thing for that though.

**Comment by searls** [comment]
It sounds like there's a pretty meaningful difference between these two, however. For example, [this post](https://www.aloucaslabs.com/miniposts/what-is-the-difference-between-w-and-w-array-literals-in-ruby) shows how `%W` can include escape sequences and evaluate interpolated expressions.

**Comment by will** [comment]
Oh huh, I'm surprised to learn something new about ruby after all this time :)

I was going to just close this now, but then I saw you added the label, so not sure if you want it still open, so I wont take any action. Feel free to close it anytime.

**Comment by searls** [comment]
Yeah, I suppose that while Standard tries to make Ruby a little more consistent across projects, it's not an attempt to narrow its expressiveness, so I think I'd be :-1: on constraining this use. Until next time!
