### ISSUE TITLE
Running the "standardrb --fix" command changes "Class.new(Interrupt)" to "Class.new(RuntimeError)" (v1.1.5)

### ISSUE THREAD

**Issue by laser** [testdouble/standard#388]
First of all - thanks for the great work. We use your product all the time and we love it :)

## Steps to Reproduce

- Ensure that standardrb gem version 1.1.5 is active
- Ensure that standardrb is on your PATH

When the following file is formatted with the `standardrb --fix` command:

```ruby
class TestClass
  FatalError = Class.new(Interrupt)
end
```

`Interrupt` is changed to `RuntimeError`

## Why Is This a Bug?

Standard is a Ruby _style_ guide, linter, and formatter. The behavior outlined in this issue demonstrates that the formatter has changed code _semantics_ and not style.

**Comment by searls** [comment]
This definitely seems weird. @koic does this look like an unhandled edge case in the associated cop?

**Comment by koic** [comment]
I've opened https://github.com/rubocop/rubocop/pull/10406 to resolve this issue.

**Comment by bbatsov** [comment]
I've added there a couple of comments myself. Seems to me that the gist of it as:

- the auto-correction here was inherently unsafe
- we probably need a different message when someone is trying to extend error classes that are not meant to be extended (e.g. `LoadError`) (or perhaps the list of those classes should be made configurable)

**Comment by camilopayan** [comment]
The fix is in the latest version of standard now too 😄

**Comment by laser** [comment]
Thanks, folks! :)
