### ISSUE TITLE
Avoid `return` in `.select do .. end` a la `return` in `.map do .. end`

### ISSUE THREAD

**Issue by jon-sully** [testdouble/standard#394]
Greetings!

Should one decide to write a `map` block as follows..

```ruby
def example
  [1, 2, 3, 4, 5].map do |n|
    if n%3 == 0
      return true
    else
      return false
    end
  end
end
# Intuitively we'd expect:
# => [false, false, true, false, false]
# But we actually get
# => false
```

Perhaps assuming that the `return` in the block would be scoped to the local iteration of each member of the enumerable, Standard flags this:

> Non-local exit from iterator, without return value. `next`, `break`, `Array#find`, `Array#any?`, etc. is preferred.

Via `Lint/NonLocalExitFromIterator`. This is a great catch from a listing standpoint and can help prevent bugs for _sure_. So thus the issue, I'm not sure why this same logic doesn't get accounted for in the `.select` method when the result / side-effect is the same.

```ruby
def example
  [1, 2, 3, 4, 5].select do |n|
    if n%3 == 0
      return true
    else
      return false
    end
  end
end
# Intuitively we'd expect:
# => [3]
# But we actually get
# => false
```

**Comment by jon-sully** [comment]
This may well be a Rubocop issue and may yet be bigger in scope (any block?) but thought I'd start by posting here! 🙏

**Comment by searls** [comment]
The conditions under which this lint can be sure that the warning is correct & safe are rather limited, which is probably why it doesn't fire in all cases. ([Doc](https://docs.rubocop.org/rubocop/cops_lint.html#lintnonlocalexitfromiterator)). If you have additional feedback, I recommend opening it on rubocop's repo

**Comment by jon-sully** [comment]
Thanks for the thought and the pointer in the right direction @searls!
