### ISSUE TITLE
Ignored files specified on command line will be scanned.

### ISSUE THREAD

**Issue by phallstrom** [testdouble/standard#400]
Hi -

If you specify an ignored file on the command line, it will still be scanned. For example:

```
% standardrb db | grep db/schema
# no output

% standardrb db/schema.rb
...
  db/schema.rb:74:14: ...
```

I can see the advantage of this, but in my use case I'm generating a subset of files to scan based on the files changed in git which sometimes results in files we'd prefer to ignore. 

How would you feel about ignoring these specified files? Or an option to ignore them even if specified?  I'm happy to do the work, just don't want to waste my time if either is a no go.

Thanks!

**Comment by searls** [comment]
Could you please research whether Rubocop's CLI behaves differently than this?

**Comment by searls** [comment]
Huzzah!
