### ISSUE TITLE
Proposal: Style/CollectionMethods

### ISSUE THREAD

**Issue by swanson** [testdouble/standard#41]
https://rubocop.readthedocs.io/en/latest/cops_style/#stylecollectionmethods

Current `standard` option is: disabled
Proposed change: enabled, default RuboCop mapping for PreferredMethods (e.g. favor `find` over `detect`)

---

👋 

Recent turned on this cop because it is annoying when someone wants to use the more obscure SmallTalk-inspired enumerable methods (`inject`, `collect`, `detect`, etc) and another person likes the more commonly used methods (`select`, `find`, `map`, etc). The later also maps more closely to other languages you might be using (namely ES6).

I see no reason to prefer the SmallTalk-style nor to spend time debating which one to use.

Downsides:
* RuboCop docs warn that there may be false positives -- was not sure if that consideration should influence inclusion in standard
* There is a performance cop that recommends `detect` -- can't say that I really care about that kind of micro-optimizing, but that might not be true for the majority

**Comment by searls** [comment]
Let's close this and track it in @danielmorrison's #39 since he opened that first and it'll have the same effect

**Comment by searls** [comment]
After reading more closely, I think #39 might be narrow enough to recommend but for the reasons I stated in [this comment on that PR](
https://github.com/testdouble/standard/pull/39#issuecomment-445465868), I think this would go too far.

**Comment by swanson** [comment]
Is it fair to say that this library intends to address formatting rather than styling? I'm having trouble distinguishing why, e.g. "prefer `find` to `detect`" goes too far compared to some of the other enabled cops:

- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EvenOdd
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MinMax
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/Casecmp
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EachWithObject
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FormatString

These seem to also "ban alias usage". Maybe there is no hard and fast rule -- in which case, no problem.

I'm totally fine with `standard` never flagging anything outside of spacing and syntax-fiddling, but I think if it starts to dip it's toes into _some_ styling cops, you might as well go all-in :)

**Comment by searls** [comment]
The answer is that we started with RuboCop's defaults and many of the rules we don't like are still in this config because we haven't run into them and no one has pointed them out. I wouldn't be surprised if we would want to disable all of those

**Comment by swanson** [comment]
Ah -- okay, that makes sense. Sorry, I had it backwards in assuming anything explicitly added was "approved".

**Comment by searls** [comment]
Yeah glancing at these, I think I'd disable all of them with the possible exception of each_with_object because that particular usage of inject/reduce is really common due to habit/lack of awareness and the expressiveness of inject/reduce is much much wider but each_with_object is much more specific and intention revealing when this is how they're used

**Comment by searls** [comment]
@swanson no it's a good point. We should broadcast that more clearly
