### ISSUE TITLE
Default Ignored directories

### ISSUE THREAD

**Issue by searls** [testdouble/standard#42]
(Suggested in #30 by @palkin)

In addition to #29, which specifies Rails-specific folders be excluded when Rails is detected, Standard should ignore obvious directories. @palkin suggested these, but we should consider what the right set of directories is:

```
    # auto-generated binstubs
    - 'bin/*'
    # temp files
    - 'tmp/**/*'
    # node_modules could contain Ruby code
    - 'node_modules/**/*'
    # vendor/ dir is used by most CI services
    - 'vendor/**/*'
```

Things to consider:

1. Additionally, we should consider whether these should be limited to `.standard.yml` or `Gemfile` relative directories. If my `pwd` happens to be in `app/lib/foo` and I happen to have a `app/lib/foo/tmp` directory, I would not want our default ignores to subsequently fail to run against it

2. Doesn't Rubocop itself have default ignores? Are we skipping those already by din of delegating to RuboCop?

**Comment by palkan** [comment]
> Doesn't Rubocop itself have default ignores? 

It turned out that it has: https://github.com/rubocop-hq/rubocop/blob/v0.61.1/config/default.yml#L60-L63.

But if you define your own `AllCops -> Exclude` directive, it overrides the default one and not merged into it. That's the default behaviour.

There is an [inherit_mode directive](https://docs.rubocop.org/en/latest/configuration/#merging-arrays-using-inherit_mode) to change this behaviour and merge configs instead.

**Comment by searls** [comment]
@palkan thanks for the context about `inherit_mode`. For this particular case I don't really care if we end up duplicating all of 3 strings.

**Comment by searls** [comment]
I suppose this raises yet another question: how should users _unignore_ a default ignore? Rubocop has a complex but expressive Include/Exclude as described by @palkan, but we just have an `ignore:` yaml directive. If we add default ignores, we'll want a way for users to unignore them (just in case they really want to lint them `node_modules/`).

Do we add an `unignore:` to the yaml just for this edge case?

**Comment by palkan** [comment]
> Do we add an unignore: to the yaml just for this edge case?

Something like `default_ignores: false` makes sense to me
