### ISSUE TITLE
Adding rubocop-rspec focus cop

### ISSUE THREAD

**Issue by dorianmariefr** [testdouble/standard#427]
https://www.rubydoc.info/gems/rubocop-rspec/1.5.0/RuboCop/Cop/RSpec/Focus

This cop would prevent `fit`, `focus: true`, etc. from being in the committed test suite

**Comment by searls** [comment]
Thank you Dorian, but Standard doesn't incorporate the rspec or rails gems, just rubocop & rubocop-performance.
