### ISSUE TITLE
Bump Rubocop to 1.31

### ISSUE THREAD

**Issue by LandonSchropp** [testdouble/standard#430]
Rubocop has added the new `--server` flag in 1.31. I'd love to be able to use it. 🙂

**Comment by LandonSchropp** [comment]
Thank you for tackling this!

I should have clarified in my original post that my team is using the standard.rb Rubocop configuration directly rather than the CLI.

In terms of integrating with the standard CLI, I believe there are six new Rubocop flags:

* `--[no-]server`
* `--restart-server`
* `--start-server`
* `--stop-server`
* `--server-status`

Maybe it's as simple as passing those flags directly to Rubocop under the hood?

**Comment by LandonSchropp** [comment]
For now, if you could bump the dependency in standard that would solve my problem. If I try to update to 1.31 in my repo, I get the following error:

```
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (~> 1.31)

    standard (~> 1.10) was resolved to 1.12.1, which depends on
      rubocop (= 1.29.1)
```

**Comment by kylefox** [comment]
@searls Could you please have another look at updating the `rubocop` dependency? 😁 

I'm running into some issues because Standard is locked to `rubocop (= 1.29.1)`:

```
Bundler could not find compatible versions for gem "rubocop":
  In snapshot (Gemfile.lock):
    rubocop (>= 1.29.1)

  In Gemfile:
    rubocop-rspec (= 2.12.1) was resolved to 2.12.1, which depends on
      rubocop (~> 1.31)

    standard was resolved to 1.12.1, which depends on
      rubocop (= 1.29.1)
```

**Comment by searls** [comment]
I believe @camilopayan is working on a dependency update release soon

**Comment by camilopayan** [comment]
Yep, v1.13.0 just out! I appreciate the patience.

**Comment by kylefox** [comment]
Thanks @camilopayan!
