### ISSUE TITLE
Lint/MixedRegexpCaptureTypes: Do not mix named captures and numbered captures in a Regexp literal.

### ISSUE THREAD

**Issue by JakubSQ** [testdouble/standard#435]
Here is my regex expression
`%r{(?<=<div>)(<br>)+|(<br>)+(?=</div>)}`

In return I receive 
```Lint/MixedRegexpCaptureTypes: Do not mix named captures and numbered captures in a Regexp literal.```

IMHO regex treats `(? ...)` as a group but it's only look behind expression but I am not sure about it.
Is there a way to solve this issue?

**Comment by searls** [comment]
Since this cop is maintained in Rubocop, I suggest opening an issue to ask about its behavior there https://github.com/rubocop/rubocop
