### ISSUE TITLE
Editor support for VS Code

### ISSUE THREAD

**Issue by searls** [testdouble/standard#44]
Submit a PR to [vscode-ruby](https://github.com/rubyide/vscode-ruby) adding Standard support

**Comment by onyxraven** [comment]
Could a very quick stop-gap for some of these be to have a quick command to output the matching rubocop file?

**Comment by twe4ked** [comment]
Related issue: https://github.com/rubyide/vscode-ruby/issues/56

**Comment by thearchduke** [comment]
Here is a quick-and-dirty standalone implementation: https://github.com/thearchduke/standardrb-vscode

**Comment by tmikeschu** [comment]
@thearchduke without more context, do you have plans to continue working on that plugin? `quick-and-dirty` makes me think you have goals to improve it? Thanks for your work! 😄

**Comment by wingrunr21** [comment]
This will be integrated with rubyide/vscode-ruby#405

**Comment by wingrunr21** [comment]
Standard support landed in `v0.22.0` of `vscode-ruby`. Recommended to use `v0.22.2` and up due to some bugs.

Note it's also recommended to use `standard` >= 0.30.0 due to #80 and 03aa4275

**Comment by searls** [comment]
Awesome, @wingrunr21! 🎉

Would you like to send a PR to link to the project and any instructions to this repo's README?

**Comment by CodingItWrong** [comment]
@wingrunr21 I gave rubyide/vscode-ruby#405 a try but I wasn't able to get the formatting working, and I don't see any instructions for standard under https://github.com/rubyide/vscode-ruby#formatting - if someone could add instructions that'd help me vet what I'm doing.

**Comment by wingrunr21** [comment]
@CodingItWrong apologies, docs haven't been updated yet. That extension has a number of fires that I'm trying to fight and documentation is a less hot one.

Standard configuration is the same as RuboCop. The VSCode configuration will provide suggestions for applicable keys.

Please take a look at some of the issues too. There are a few bugs related to that PR that I need to address.

**Comment by stevenharman** [comment]
I think we can close this one too as of #100. Yeah?

**Comment by CodingItWrong** [comment]
Y'all can feel free to go ahead and close; I will give the new docs a try and see if I have any feedback on the updates docs. I can open a new issue or PR for anything I find.
