### ISSUE TITLE
Hash subset syntax flagged

### ISSUE THREAD

**Issue by mperham** [testdouble/standard#442]
Ruby allows you to use `<=` to check for a subset of a Hash which I'm using as a test assertion (as the hash also includes some racy, unpredictable data):

```
hash = {time: "2022-07-22T22:03:00Z", p: 1, f: 0, some: "unpredictable timing"} 
assert({time: "2022-07-22T22:03:00Z", p: 1, f: 0} <= hash)
```

https://stackoverflow.com/a/35135438/1494519

This syntax is flagged by Style/YodaCondition. Is this intended? Is there an alternate way you'd suggest?

**Comment by searls** [comment]
Woah! Shouldn't be surprised to be learning about a feature of hashes I never knew from @mperham! Super cool!

Reading the Rubocop docs on this, I think this is definitely a bug in that YodaCondition cop. Would you mind opening an issue on rubocop/rubocop and linking back to this one?

**Comment by mperham** [comment]
As always, thank you Justin.
