### ISSUE TITLE
.standard.yml ignore setting is ignored (ha!) when passing in a list of files from the command line

### ISSUE THREAD

**Issue by brent-yearone** [testdouble/standard#465]
I've been working on creating a git pre-commit hook that runs standard in fix mode, to ensure all my devs do the right thing. The pre-commit hook is a one-liner: `git diff --cached --name-only | xargs ~/.rbenv/shims/bundle exec standardrb --fix`

The `git diff --cached --name-only` bit gets a list of changed files from the git diff. It works great, in the sense that standardrb is run only on the changed files, which is exactly what I'm after. However, there's one major issue.

In my .standard.yml file, I've got this stanza:

```yml
ignore:
  # Directories & file types
  - '.gitconfig'
  - 'config/githooks/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - '*.md'
  - '*.yml'
```

If I'm modifying the .standard.yml file, when I commit it, the pre-commit hook dutifully passes the filename along, and to my surprise, standardrb flags the file as having formatting issues! It looks to me like the `ignore` stanza in the config file isn't applied when the CLI is handed a list of files. Am I misunderstanding something? Is there a workaround? Or is this a flat-out bug?

**Comment by searls** [comment]
Yes, that's correct. I believe this is how Rubocop behaves as well. If you pass Standard an explicit filename that's ignored, it assumes you mean to lint it. I think that's the right behavior.

My advice would be to just run Standard against the full project. Rubocop's caching is good enough that it shouldn't be a significant performance difference on anything but absolutely massive projects.

**Comment by brent-yearone** [comment]
That makes sense. I wasn't sure which way the override would work. I'm closing this out as "works as intended." Thanks!
