### ISSUE TITLE
Clarify precedence between OR operator and inline ternary

### ISSUE THREAD

**Issue by jon-sully** [testdouble/standard#471]
Howdy! Just wanted to post in and ask if Standard would be up for flagging combinations of the OR operator with the ternary operator as a "needs parenthesis to clarify precedence".

Example:

If one writes code like

```ruby
val = method_might_be_nil || fall_back_condition ? :foo : :bar
```

They either mean OR-first:

```ruby
val = (method_might_be_nil || fall_back_condition) ? :foo : :bar
```

Or ternary-first:

```ruby
val = method_might_be_nil || (fall_back_condition ? :foo : :bar)
```

but in the absence of explicit parenthesis, Ruby chooses OR-first logical precedence. Bit me in the foot since I was presuming the latter, but I think it may just be better for everyone involved if Standard enforces a parenthesis requirement for the OR + Ternary combo.

**Comment by searls** [comment]
Seems like the sort of thing we'd be open to. Is there an existing Rubocop rule that can do this?

**Comment by jon-sully** [comment]
Looks like https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TernaryParentheses is available — `require_parentheses_when_complex` seems like the right level of callout to me. WDYT?

**Comment by jon-sully** [comment]
Ah, this would be a change from what's currently configured for Standard. It's currently set to [`require_no_parentheses`](https://github.com/testdouble/standard/blob/830205c0aed481256b0a8e97874b2f1a755c8ef8/config/base.yml#L1801) (the default for that cop)

**Comment by searls** [comment]
Made the rule change. It should land in the next release

**Comment by jon-sully** [comment]
Sweet! Thanks @searls!
