### ISSUE TITLE
Do you want a LSP server in this project?

### ISSUE THREAD

**Issue by will** [testdouble/standard#472]
Before, I was using solargraph and doing some not-great monkeypatches to get it to use standard instead of raw rubocop. But I realized all I really wanted from solargraph was just diagnostics and formatting and none of the other LSP features from solargraph. 

Over the last few days I've made a custom LSP server that just does formatting and diagnostics, and with a few tricks, like reusing the huge rubocop_config_store, it can do things nearly real-time. Close enough for me at least:

https://user-images.githubusercontent.com/1973/197632689-750d9ecf-e519-4696-9620-33c5ec52c434.mov

I wonder if this is something you'd like in the standard project itself? It could be nice to just run `standard --lsp` or something.  It's a bit under 200loc (no tests yet though) and takes one dependency to `language_server-protocol`

**Comment by searls** [comment]
I love this. I'd absolutely love to pull this in

**Comment by searls** [comment]
How would you like to proceed, @will?

**Comment by will** [comment]
I have it working in a branch, was starting in on some tests. I'll open up a draft pr so you can check it out in progress.

**Comment by searls** [comment]
One thing I'm super curious about, because @tenderlove and I have been talking about LSPs in Ruby and vim/nvim vs. VS Code, is how batteries-included this can or should be, and what it would take to… I dunno, offer an official VS Code extension?

**Comment by will** [comment]
I've never used vscode, so I can't help on that part. The nvim 0.8 configuration I'm using for this is:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "ruby",
  group = vim.api.nvim_create_augroup("RubyLSP", { clear = true }),
  callback = function()
    vim.lsp.start {
      name = "standard",
      cmd = { "standardrb", "--lsp" },
      -- on_attach = your on attach fn with 'keybindings you want, etc
    }
  end
end,
})
```

which is pretty minimal. I'll probably make it a little fancier and try and see if you have a Gemfile in the root dir and do `bundle exec` first if so, but that's not too bad. I wouldn’t imagine vscode would take too much more but I'm not sure.

**Comment by searls** [comment]
There's no shortage of prior art, at least. Just wanted to flag it and I know Aaron had at least briefly looked at it

**Comment by weizheheng** [comment]
I came across this and tried running the new --lsp introduced by Will's PR. It's definitely an improvement in the development experience. With standardrb --lsp, I no longer need solargraph in my dev setup. 

Thank you very much for both of your works.
