### ISSUE TITLE
Create a Code Climate engine for Standard

### ISSUE THREAD

**Issue by searls** [testdouble/standard#48]
Presumably, we'll want to fork or (less invasively) extend the [codeclimate-rubocop](https://github.com/codeclimate/codeclimate-rubocop) engine. I'd really like the opinion of someone from Code Climate's input on how to best do this (cc/ @brynary 🙇‍♂️) 

The spec for writing custom engines is [here](https://github.com/codeclimate/spec/blob/master/SPEC.md)

**Comment by pnomolos** [comment]
@searls Can I claim this one?  Would like it for internal use.

**Comment by searls** [comment]
@pnomolos it's all yours!

**Comment by jfi** [comment]
@pnomolos Was any progress ever made on this? Thanks!

**Comment by jakeonfire** [comment]
sounds like we need a new assignee

**Comment by pnomolos** [comment]
@jakeonfire @jfi Yes we probably need a new assignee if someone's able to take this.  My plate is unfortunately way too full at the moment :(

**Comment by jakeonfire** [comment]
i may free up in a week or so. any advice @filipesperandino or @wfleming?
> Presumably, we'll want to fork or (less invasively) extend the codeclimate-rubocop engine. I'd really like the opinion of someone from Code Climate's input on how to best do this

**Comment by filipesperandio** [comment]
Hey!
The SPEC file got moved, it is now [here](https://github.com/codeclimate/platform/tree/master/docs/analyzers) and [here](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md)
The rubocop is a good example to follow, and a something to remember is that plugins don't have network access when analyzing files.

**Comment by onyxraven** [comment]
Presumably, one way to get 'somewhat' there is to use the [remote file fetch](https://docs.codeclimate.com/docs/advanced-configuration#configuration-file-structure-and-content) to download the [base/config](https://github.com/testdouble/standard/blob/master/config/base.yml) and set the [engine channel to 90](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop). But a real engine is obviously better.

**Comment by jakeonfire** [comment]
i have an engine working locally: https://github.com/jakeonfire/codeclimate-standard
not sure what next steps are. filling out [this form](https://codeclimate.com/dev_form/) leads me to a [getdrip.com 404 page](https://www.getdrip.com/forms/8161429/submissions) 🤔 
@filipesperandio would you mind sending me an invite to the Code Climate Developer Slack Channel?

**Comment by jakeonfire** [comment]
@onyxraven tried that, but it doesn't respect the standard rules over rubocop ones in the engine so you get conflicting suggestions running standard/rubocop locally vs codeclimate.

**Comment by filipesperandio** [comment]
@jakeonfire Will look what is going in the morning and send you an invite! 👍

**Comment by filipesperandio** [comment]
It is out https://github.com/codeclimate/codeclimate/releases/tag/v0.85.18

**Comment by searls** [comment]
Huzzah! That's awesome Filipe!

**Comment by searls** [comment]
@filipesperandio if you have a minute to share what setup instructions would look like I'd love to get that on the readme!

**Comment by filipesperandio** [comment]
On `.codeclimate.yml`:
```yml
plugins:
  standard:
    enabled: true
    channel: beta
```
`beta` can get updated more frequently, but `stable` is matching it up now, so `channel` is not really required.

You can check Jake's repo too: https://github.com/jakeonfire/codeclimate-standard

**Comment by searls** [comment]
Thanks! added a wiki page https://github.com/testdouble/standard/wiki/CI:-Code-Climate

**Comment by jakeonfire** [comment]
let me know if you run into any issues @searls
