### ISSUE TITLE
Editor Support for RubyMine

### ISSUE THREAD

**Issue by searls** [testdouble/standard#49]
I don't know anything about writing RubyMine extensions, and it looks like RuboCop integration [comes out of the box](https://www.jetbrains.com/help/ruby/rubocop.html), so I'm unsure how to proceed. Any ideas?

**Comment by searls** [comment]
The RubyMine team has [opened a public issue to track this](https://youtrack.jetbrains.com/issue/RUBY-23260)

**Comment by hurricup** [comment]
To make it work with RubyMine we need an `--stdin` option. I'd expected that all RuboCop options works from the box. Are there any plans to support it?

**Comment by hurricup** [comment]
Oh, rly? I've checked help and tried `-s` and it didn't work. Will check `--stdin`, sorry :)

**Comment by searls** [comment]
At the bottom of `standardrb --help`, it says:

```
Standard also forwards most CLI arguments to RuboCop. To see them, run:

  $ rubocop --help

```

**Comment by hurricup** [comment]
@searls which says, that `-s` or `--stdin` works. But `-s` doesn't.

**Comment by mjbellantoni** [comment]
Howdy @searls and @hurricup.  I've just tried this with v0.0.39 of `standard` and both `-s` and `--stdin` seem to work as expected.
```bash
(~/Development/standard) ./exe/standardrb --version
0.0.39
(~/Development/standard) echo "[ 1 ]" | ./exe/standardrb -s foo.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `standardrb --fix` to automatically fix some problems.
  foo.rb:1:2: Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside array brackets.
  foo.rb:1:4: Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside array brackets.

Notice: Disagree with these rules? While StandardRB is pre-1.0.0, feel free to submit suggestions to:
  https://github.com/testdouble/standard/issues/new
(~/Development/standard) echo "[ 1 ]" | ./exe/standardrb --stdin foo.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `standardrb --fix` to automatically fix some problems.
  foo.rb:1:2: Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside array brackets.
  foo.rb:1:4: Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside array brackets.

Notice: Disagree with these rules? While StandardRB is pre-1.0.0, feel free to submit suggestions to:
  https://github.com/testdouble/standard/issues/new
```

**Comment by searls** [comment]
@mjbellantoni what's our next step do you think? I'm not a RubyMine user so I don't know what our next step should be

**Comment by mjbellantoni** [comment]
@searls I think the next step is that the RubyMine team needs to do whatever they need to do.  I think they were blocked by the belief that `-s` and `--stdin` weren't working.  I'll update the [ticket on their tracker](https://youtrack.jetbrains.com/issue/RUBY-23260) to let them know they shouldn't be blocked by this.  Make sense?

**Comment by searls** [comment]
Thanks!

**Comment by mjbellantoni** [comment]
The RubyMine team has marked [their ticket ](https://youtrack.jetbrains.com/issue/RUBY-23260)as fixed in version "2019.2 EAP4".

**Comment by searls** [comment]
Awesome, will mark this closed until I hear otherwise!

**Comment by rohitpaulk** [comment]
For anyone landing here and looking for instructions on how to enable standardrb in Rubymine: https://www.jetbrains.com/help/ruby/rubocop.html#disable_rubocop.

<img width="740" alt="Screenshot 2022-05-23 at 19 25 48" src="https://user-images.githubusercontent.com/3893573/169883280-9080526c-dd14-4160-a087-a72ebb7c53f8.png">

**Comment by searls** [comment]
Thanks! I dropped a very simple wiki page for anyone looking there: https://github.com/testdouble/standard/wiki/IDE:-RubyMine -- this was already linked in the README
