### ISSUE TITLE
Lint/ParenthesesAsGroupedExpression should _not_ be autocorrected

### ISSUE THREAD

**Issue by SampsonCrowley** [testdouble/standard#514]
![Screenshot 2023-01-23 at 8 34 29 PM](https://user-images.githubusercontent.com/22461638/214207080-d1bc0d6c-1168-497f-b761-cb3e5c7c4359.png)

![Screenshot 2023-01-23 at 8 33 49 PM](https://user-images.githubusercontent.com/22461638/214207188-1f4c4e56-db0c-4183-8762-a40bd556dade.png)

![Screenshot 2023-01-23 at 8 35 46 PM](https://user-images.githubusercontent.com/22461638/214207213-bb16a14c-66ff-420d-b3ae-29646e23ddec.png)

These two statements are _not_ equivalent. and autocorrecting them is very dangerous

**Comment by koic** [comment]
It looks like an issue resolved in RuboCop 1.40:
https://github.com/rubocop/rubocop/issues/11192

Standard already uses 1.42:
https://github.com/testdouble/standard/blob/v1.22.1/standard.gemspec#L22

Wouldn't updating to the latest Standard solve the issue?

**Comment by SampsonCrowley** [comment]
@koic that is likely, this is a legacy codebase that is has a lot of red tape to update anything. only opened the issue because I found no reference to it at all, including mention that it's been a problem already, and already been fixed.

just assumed it was a design choice that should be modified, not a bug with rubocop
