### ISSUE TITLE
advertised VSCode extension speedup outside VSCode

### ISSUE THREAD

**Issue by iftheshoefritz** [testdouble/standard#528]
I just want to make sure I understand the announcement that the VSCode standardrb extension is faster now. Are any of these assumptions incorrect:

1. the speedup is due to having an LSP server process that is long-lived, rather than starting the executable from scratch on every save
1. any plugin (for any editor) that can speak LSP to the standardrb server should be able to benefit in the same way
1. a long-running process that invokes rubocop's code directly using `Rubocop::Runner` already has the same benefit, because it isn't loading everything from scratch for every invocation.

The last point may seem quite niche, but I'm thinking of the [solargraph-standardrb plugin](https://github.com/bekicot/solargraph-standardrb/blob/master/lib/solargraph-standardrb.rb). Solargraph loads the plugin at startup time, and the plugin interacts with rubocop directly.

I think solargraph may only support linting, not formatting, so there is some work to do still.

**Comment by searls** [comment]
> 1. the speedup is due to having an LSP server process that is long-lived, rather than starting the executable from scratch on every save

Yes.

> 2. any plugin (for any editor) that can speak LSP to the standardrb server should be able to benefit in the same way

"Yes". The LSP spec is written by Microsoft and their implementation is the most robust. As a result, I'm not super confident that LSP clients designed to help plugin authors of other editors will work perfectly without some tweaks.

The `--lsp` server mode was initially  written by @will for Neovim support. Those are the only two tools using it now, to my knowledge

> 3. a long-running process that invokes rubocop's code directly using `Rubocop::Runner` already has the same benefit, because it isn't loading everything from scratch for every invocation.

Yes, this theoretically should be equivalent! I had a really bad experience personally trying to configure either solargraph or ruby-lsp for this purpose, which is what led me to do my own bespoke extension that we could control with more fine-grained integration to our LSP implementation. This approach will also allow us to make a few minor performance optimizations (like caching results against known document hashes, incremental document syncing backed by an in-memory cache of the full documents, etc.), but I think anything that takes the same approach of keeping a `Rubocop::Runner` in resident memory and invokes it using its `stdin` mode should perform within the same order of magnitude as compared to shelling out

**Comment by iftheshoefritz** [comment]
Brilliant! Thanks for this work :)
