### ISSUE TITLE
Rules conflicting with Rubocop

### ISSUE THREAD

**Issue by devaniljr** [testdouble/standard#529]
I tried using Standard in my project's VS Code, but it keeps insisting to use double quotes instead of single quotes. But RuboCop has a different opinion, so on CI it always breaks. Is there any way to reconcile the two rules?

**Comment by searls** [comment]
Standard is an alternative to Rubocop. It uses the Rubocop rules and API as its engine, but it is designed to be run _instead of_ Rubocop and not in addition to it. As a result, I'd recommend either considering adopting Standard over Rubocop (e.g. replace your CI actions with `standardrb` or `rake standard`) or find another editor extension to use.

If you need to add Rubocop extensions (like rubocop-rspec or rubocop-rails), you can [load those as part of your Standard config](https://github.com/testdouble/standard#how-do-i-use-standard-with-rubocop-extensions-or-custom-rules)
