### ISSUE TITLE
The help message breaks parsing after using --format json

### ISSUE THREAD

**Issue by cschneid** [testdouble/standard#53]
If I call standardrb with: `standardrb --format json > output.json`, the message about disagreeing with defaults is in the output at the end, which prevents a direct parse of that json file, without further preprocessing.

I'd be happy to fix this myself, but not sure the approach you'd like.

:one: STDERR for the message
:two: Don't output the message on an explicit format flag
:three: Something else?

**Comment by searls** [comment]
Hey Chris! Great to hear from you. 

I suspect the right thing to do is to make this message print from the `StandardFormatter` class instead. We probably just need to figure out what the final "everything is really all done now" hook is.
