### ISSUE TITLE
parallel: true broken for ale

### ISSUE THREAD

**Issue by thewatts** [testdouble/standard#530]
👋  First off - I'm so thankful for this gem and what it provides our team.

I'm in no way jumping in here to complain - I understand that most of what this app does is delegate out to rubocop, and what could be going on is likely a rubocop issue.

I _did_ want to post something here though, in case someone ran into the same issue (I haven't found a related issue yet on this repo, or rubocop).

**Important context** - we use a custom `.standard.yml` file - which includes the options in the README, specifically `parallel: true`.

---

I use [ale](https://github.com/dense-analysis/ale) for linting/auto-fixing, and recently noticed that in between different projects, standard fixing was working on save, and in others - it wasn't.

Digging into this more specifically - I found that the jump from standard [1.13 to 1.14](https://github.com/testdouble/standard/blob/main/CHANGELOG.md#1140) causes Ale to fail to run its fix command.

Granted, the only changes here are upgrading rubocop to [1.32.0](https://github.com/rubocop/rubocop/releases/tag/v1.32.0)

To clarify here - listing _does_ work, fixing _does not_.

In digging into the changes, it looks like [changes were made to the rubocop parallel option](https://github.com/rubocop/rubocop/issues/10613)

### The current fix:
Setting `parallel` back to `false` fixes the problem - and ale works once again.

---

### 1.13
https://user-images.githubusercontent.com/1141717/221702761-d2537542-eef2-4caa-935e-efb23a7dc2aa.mp4

### 1.14
https://user-images.githubusercontent.com/1141717/221702811-59f7d865-1902-41be-bfc8-9249799dc59f.mp4

**Comment by searls** [comment]
Thanks for sharing. Indeed, the fact this breaks on a release that did nothing but bump rubocop has me assuming this is a Rubocop issue.

I think other than raising a hand in that issue (maybe @koic knows something?), I'd recommend as a next step testing Ale with the rubocop release before and after this change. If it works, then maybe the problem is with how Standard is invoking Rubocop's runner

**Comment by searls** [comment]
To confirm this is the same issue as #536, I verified ale is invoking `standardrb` with `--stdin` (as you'd expect) [source](https://github.com/dense-analysis/ale/blob/fbae1bc1937ce69fa80b4b32d178ce666fd5c07c/ale_linters/ruby/standardrb.vim#L14)

**Comment by searls** [comment]
Okay, this should be fixed in 1.25.1
