### ISSUE TITLE
LSP server fails to initialise in Helix editor

### ISSUE THREAD

**Issue by benjamineskola** [testdouble/standard#542]
When using `standardrb --lsp` in Helix I get error messages in the log:

```
2023-03-31T18:05:48.225 helix_lsp [ERROR] failed to initialize language server: failed to parse: invalid type: boolean `true`, expected struct ExecuteCommandOptions
```

As this worked in Neovim, I initially reported the bug to Helix: https://github.com/helix-editor/helix/issues/6506 who responded:

> This is a bug in StandardRB: it's sending "executeCommandProvider":true in the initialization response but that field can't be a boolean in the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#executeCommandOptions

**Comment by searls** [comment]
Seems like the expected interface is [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#executeCommandOptions)
