### ISSUE TITLE
Fix CircleCI integration

### ISSUE THREAD

**Issue by searls** [testdouble/standard#58]
Prior to merging any new features, we need to figure out why CircleCI isn't running for PRs against the app. 

See #57, #55

**Comment by edwardloveall** [comment]
I'm not totally sure, but it _might_ be as simple as changing settings here: https://circleci.com/gh/testdouble/standard/edit#advanced-settings

**Comment by searls** [comment]
Thanks, for whatever reason this is off by default for OSS!!!?!!??!?!?!11

<img width="846" alt="screen shot 2018-12-31 at 10 36 52 am" src="https://user-images.githubusercontent.com/79303/50563093-08bc1280-0ce8-11e9-9994-537e939f1449.png">

**Comment by searls** [comment]
@edwardloveall maybe try throwing an empty commit in your PR to tickle circle?

**Comment by searls** [comment]
Fixed
