### ISSUE TITLE
Only print "--fix to automatically fix some problems." when some problems are fixable

### ISSUE THREAD

**Issue by searls** [testdouble/standard#60]
We currently print  `standard: Run `standardrb --fix` to automatically fix some problems.` unnecessarily. Stop printing it when:

- [x] `--fix` was used in the run (fixed by #69)
- [ ] none of the detected problems were (safely) autofixable

Code is in the lib/standard/formatter.rb

**Comment by PlanetEfficacy** [comment]
It looks like @emilianoLeite fixed this in https://github.com/testdouble/standard/pull/77

**Comment by searls** [comment]
Yep, missed that it wasn't tagged. Thanks!
