### ISSUE TITLE
Passing bare directories to check doesn't work

### ISSUE THREAD

**Issue by cschneid** [testdouble/standard#64]
### Directory full of ruby files:

```
› ls -l lib/*.rb | wc -l
      28
```

### Run standard on the whole dir:
```
› standardrb lib
```

No output, not even the post-check notice. `--format json` says 0 files checked.

### Run on a specific file in that dir:

This works fine - shows I have things to fix.

```
› standardrb lib/histogram.rb
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
standard: Run `standardrb --fix` to automatically fix some problems.
  lib/histogram.rb:45:9: Layout/DotPosition: Place the . on the previous line, together with the method call receiver.
  lib/histogram.rb:57:23: Layout/SpaceAfterComma: Space missing after comma.
  lib/histogram.rb:58:19: Layout/SpaceBeforeBlockBraces: Space missing to the left of {.
  lib/histogram.rb:60:1: Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body end.

Notice: Disagree with these rules? While StandardRB is pre-1.0.0, feel free to submit suggestions to:
  https://github.com/testdouble/standard/issues/new
```

### Running with a glob works

A more explicit glob pattern appears to work:

```
standardrb "./lib/**/*.rb"

# ... lots of correct output
```

### Versions:

```
› standardrb --version
0.0.24

› ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]
```

**Comment by searls** [comment]
Great point! FWIW, this matches Rubocop's behavior, but it sure seems like we ought to be able to solve this ourselves by massaging the input a bit. 

It'll probably involve changing what we pass in here: https://github.com/testdouble/standard/blob/master/lib/standard/merges_settings.rb#L10

**Comment by cschneid** [comment]
I don't particularly need this feature, since the glob works fine, but it did trip me up since the readme had it, or at least appears to:

```
You can optionally pass in a directory (or directories) using the glob pattern. Be sure to quote paths containing glob patterns so that they are expanded by standardrb instead of your shell:

$ bundle exec standardrb "lib/**/*.rb" test
```

Is this simply a readme bug, rather than trying to be more clever with inputs?

**Comment by searls** [comment]
Feel free to reword it if it'd be more clear!

**Comment by jmkoni** [comment]
Just tested this running `standardrb --fix spec` and it fixed every issue in my specs. Feel free to reopen if you feel this is still an issue.
