### ISSUE TITLE
Disable Style/DateTime

### ISSUE THREAD

**Issue by twe4ked** [testdouble/standard#82]
> This cop checks for consistent usage of the `DateTime` class over the `Time` class. **This cop is disabled by default** since these classes, although highly overlapping, have particularities that make them not replaceable in certain situations when dealing with multiple timezones and/or DST.
>
> – https://docs.rubocop.org/en/latest/cops_style/#styledatetime

Since this isn't a 100% rule I think it should be disabled. Thoughts?

**Comment by searls** [comment]
Yeah, also with our gathering heuristic of not telling people what method they should call when given multiple options
