### ISSUE TITLE
Is there a way to set cop-specific attributes?

### ISSUE THREAD

**Issue by grantbdev** [testdouble/standard#88]
I know that the goal of this project is to reduce configuration, but there are a couple cops in Standard that my company currently has special configuration for in our `.rubocop.yml`:

1. `Lint/UselessAccessModifier` doesn't know about all possible methods that could create a context where you could use an access modifier such as `private`. See: https://github.com/rubocop-hq/rubocop/issues/3422. We use the `ContextCreatingMethods` config attribute to let the cop know that `ActiveSupport::Concern#included` can have a `private` that is **not** useless.
2. `Rails/UnknownEnv` is managed by the `Environments` config attribute. This can be app-specific and we have environments that are not in the default list.

Is there a way to maintain those config attribute settings with Standard?

**Comment by searls** [comment]
I find both of these points compelling enough to turn them off. The utility of both is middling, and it sounds like they both have issues that prevent them from being reliable in all cases (the former, in the implementation; the latter, conceptually)

**Comment by searls** [comment]
Landed in 0.0.33
