### ISSUE TITLE
Proposal: Disable Rails/SkipsModelValidations

### ISSUE THREAD

**Issue by grantbdev** [testdouble/standard#89]
My team currently completely disables [`Rails/SkipModelValidations`](https://rubocop.readthedocs.io/en/latest/cops_rails/#railsskipsmodelvalidations) in RuboCop. The methods are sharp knives, but I am not sure they are worthy of always being avoided. I am curious to hear how other Rails projects handle this.

**Comment by searls** [comment]
I think because there are valid cases in which skipping validations is reasonable (easy example: the model has been validated just previously and those validations are particularly expensive/taxing to invoke), this is wrong to have enabled for StandardRB.
