### ISSUE TITLE
SemanticBlocks collides with Style/RedundantBegin

### ISSUE THREAD

**Issue by wadetandy** [testdouble/standard#94]
Whenever the `Standard/SemanticBlocks` rule autofixes a block which also matches rubocop's built-in `Style/RedundantBegin` rule, the autofix results in invalid ruby:

```ruby
def do_something(array)
  value = array.map do |item|
    begin
      maybe_fail(item)
    rescue
      handle_error
    end
  end
end
```

running `bundle exec standardrb --fix` on the above results in

```ruby
def do_something(array)
  value = array.map { |item|
    
      maybe_fail(item)
    rescue
      handle_error
    
  }
end
```

Have created a reproduction repo [here](https://github.com/wadetandy/standardrb-semantic-blocks-repro).

**Comment by searls** [comment]
tbqh the fact that `Style/RedundantBegin` behaves differently post-2.3 had me almost wanting to eliminate it yesterday so I'm open to waffle on it. I don't know how strongly folks feel about it

**Comment by wadetandy** [comment]
My 2 cents: it definitely doesn’t match our org’s typical style (use braces for one liners and do/end for multi-line), but it wasn’t a big enough deal to not try out standard. But if it went away I’d be be in favor.

**Comment by wadetandy** [comment]
Further feedback: ran into a much more complicated example in the codebase I'm converting where a `SemanticBlocks` error was thrown, though this time the autofixer was not able to handle it for me.  To satisfy it and ruby's parser, I had to turn this:

```ruby
value = object.some_method :arg1, arg2: :val do |something|
  transform_item(something)
end
```

into this: 

```ruby
value = object.some_method :arg1, arg2: :val, &->(something) {
  transform_item(something)
}
```

I think this is far harder to read, and there are some on my team who wouldn't quite know how to make this conversion.  If SemanticBlocks does remain in standard, I'd suggest only matching cases where the autofixer can handle the change.

**Comment by CodingAnarchy** [comment]
Braces for one-liners and do/end for multi-line blocks has also been a much more common standard than semantic blocks in my experience, for whatever that's worth.
