### ISSUE TITLE
Trailing comma with clamped brackets

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/standard#95]
The following code generates a trailing comma error:

```ruby
assert_equal({
  tags: ["class:test_fails_enqueue_job",
         "queue:default",
         "adapter:aqueduct_double_publish",
         "executions:0", # count isn't incremented until `perform_now`
         "error:runtime_error"]}, payload)
```

When opening/closing brackets for an array are clamped to the elements, trailing commas should not be required (even if multi-line).

Possibly related to #25

**Comment by jmkoni** [comment]
Looks like this is fixed now... during one upgrade or another 😅
